Repository ceph/ceph-csi, pull requests merged in 2019-10, with the labels that each got.

#575 Change default csi liveness ports to ones less commonly used
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin.yaml
Labels: backport-to-release-v1.2.0, release-1.2.2

#666 Format ext4 with lazy_journal_init
  pkg/rbd/nodeserver.go
Labels: Priority-0, backport-to-release-v1.2.0

#670 increase sidecar timeout to 150s from 60s
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
Labels: backport-to-release-v1.2.0

#645 update registration directory name
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin.yaml
Labels: backport-to-release-v1.2.0

#644 Fix volsize for cephfs and rbd
  pkg/cephfs/controllerserver.go
  pkg/cephfs/volumeoptions.go
  pkg/rbd/controllerserver.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: backport-to-release-v1.2.0

#681 reuse existing code for size Roundoff
  pkg/util/util.go
Labels: backport-to-release-v1.2.0

#679 Handle EACCESS error from 'ceph rbd task add remove'
  pkg/rbd/rbd_util.go
Labels: backport-to-release-v1.2.0

#664 Added forcecephkernelclient as startup parameter to force enabling ceph
  cmd/cephcsi.go
  docs/deploy-cephfs.md
  pkg/cephfs/driver.go
  pkg/cephfs/volumemounter.go
  pkg/util/util.go
Labels: backport-to-release-v1.2.0
