Repository ceph/ceph-csi, pull requests merged in 2019-07, with the labels that each got.

#459 Replace noexec with debug mountflag for cephfs
  examples/cephfs/storageclass.yaml
Labels: release-1.1.0

#456 support mountflags during nodepublish in rbd
  examples/rbd/storageclass.yaml
  pkg/rbd/nodeserver.go
Labels: release-1.1.0

#454 Add nil check for process
  pkg/cephfs/util.go
Labels: release-1.1.0

#391 Support mounting and deleting version 1.0.0 RBD volumes
  cmd/cephcsi.go
  docs/deploy-rbd.md
  pkg/rbd/controllerserver.go
  pkg/rbd/errors.go
  pkg/rbd/nodeserver.go
  pkg/rbd/rbd.go
  pkg/rbd/rbd_util.go
Labels: release-1.1.0

#405 Driver version updated to 1.1.0
  deploy.sh
  deploy/cephfs/helm/Chart.yaml
  deploy/cephfs/helm/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/helm/Chart.yaml
  deploy/rbd/helm/values.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  pkg/cephfs/driver.go
  pkg/rbd/rbd.go
Labels: DNM

#469 Update driver version during build time
  Makefile
  cmd/cephcsi.go
  pkg/cephfs/driver.go
  pkg/cephfs/mountcache.go
  pkg/rbd/rbd.go
  pkg/util/util.go
Labels: release-1.2.0

#457 Implement NodeStage and NodeUnstage for rbd
  deploy/cephfs/helm/templates/nodeplugin-daemonset.yaml
  deploy/cephfs/helm/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/helm/templates/nodeplugin-daemonset.yaml
  deploy/rbd/helm/values.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  e2e/cephfs.go
  e2e/rbd.go
  e2e/utils.go
  examples/rbd/storageclass.yaml
  pkg/cephfs/mountcache.go
  pkg/cephfs/nodeserver.go
  pkg/cephfs/util.go
  pkg/cephfs/volume.go
  pkg/cephfs/volumemounter.go
  pkg/rbd/nodeserver.go
  pkg/rbd/rbd_attach.go
  pkg/rbd/rbd_util.go
  pkg/util/util.go
  pkg/util/validate.go
Labels: release-1.2.0

#310 Implement metrics for cephfs CSI driver.
  pkg/cephfs/nodeserver.go
Labels: Priority-0, release-1.2.0

#437 Cephfs: Remove user creation for every volume
  pkg/cephfs/cephuser.go
  pkg/cephfs/controllerserver.go
  pkg/cephfs/mountcache.go
  pkg/cephfs/nodeserver.go
  pkg/cephfs/volume.go
Labels: release-1.2.0

#445 Use --keyfile option to pass keys to all Ceph CLIs
  deploy/cephfs/helm/templates/nodeplugin-daemonset.yaml
  deploy/cephfs/helm/templates/provisioner-statefulset.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/helm/templates/nodeplugin-daemonset.yaml
  deploy/rbd/helm/templates/provisioner-statefulset.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  pkg/cephfs/cephfs_util.go
  pkg/cephfs/cephuser.go
  pkg/cephfs/controllerserver.go
  pkg/cephfs/fsjournal.go
  pkg/cephfs/mountcache.go
  pkg/cephfs/nodeserver.go
  pkg/cephfs/volume.go
  pkg/cephfs/volumemounter.go
  pkg/cephfs/volumeoptions.go
  pkg/rbd/controllerserver.go
  pkg/rbd/nodeserver.go
  pkg/rbd/rbd_attach.go
  pkg/rbd/rbd_util.go
  pkg/util/cephcmds.go
  pkg/util/credentials.go
  pkg/util/stripsecrets.go
Labels: release-1.2.0

#494 unmap rbd volume if nodestage fails
  pkg/rbd/nodeserver.go
Labels: Priority-0, release-1.2.0

#503 docs: add special config steps to make CephFS CSI v1.1.0
  docs/deploy-cephfs.md
Labels: cephfs

#460 Fix pluginpath for cephfs
  cmd/cephcsi.go
  docs/deploy-cephfs.md
  pkg/cephfs/driver.go
  pkg/rbd/rbd.go
  pkg/util/cachepersister.go
  pkg/util/util.go
Labels: release-1.2.0

#502 cephfs: set pool layout and the mode when creating fs subvolumes and not when creating subvolume group `csi`
  pkg/cephfs/volume.go
Labels: bug, cephfs, release-1.2.0

#498 add validation to check if stagingPath exists
  pkg/cephfs/nodeserver.go
  pkg/rbd/nodeserver.go
  pkg/util/util.go
  pkg/util/validate.go
Labels: Priority-0, release-1.2.0
