Repository ceph/ceph-csi, pull requests merged in 2019-08, with the labels that each got.

#512 Implement metrics for RBD plugin
  cmd/cephcsi.go
  pkg/cephfs/driver.go
  pkg/cephfs/nodeserver.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/utils.go
  pkg/rbd/nodeserver.go
  pkg/rbd/rbd.go
Labels: Priority-0, release-2.0.0

#530 docs: Clarify that Nautilus means >=14.2.2
  README.md
Labels: DNM

#522 Make parameter `pool` optional in CephFS storageclass
  docs/deploy-cephfs.md
  e2e/cephfs.go
  e2e/utils.go
  examples/cephfs/storageclass.yaml
  pkg/cephfs/volume.go
  pkg/cephfs/volumeoptions.go
Labels: Priority-0, release-2.0.0

#525 remove post validation of rbd device
  pkg/rbd/rbd_attach.go
Labels: Priority-0, release-2.0.0

#542 e2e: do not fail deleting resources when "resource not found"
  e2e/e2e_test.go
Labels: cleanup, release-1.2.0

#517 provisioners: add reconfiguring of PID limit
  cmd/cephcsi.go
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.13/helm/templates/provisioner-statefulset.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.14+/helm/templates/provisioner-deployment.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.13/helm/templates/provisioner-statefulset.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/helm/templates/provisioner-deployment.yaml
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  pkg/util/pidlimit.go
  pkg/util/pidlimit_test.go
Labels: Priority-0, release-1.2.0

#531 Add support to use ceph manager rbd command to delete an image
  pkg/rbd/rbd_util.go
Labels: Priority-0, release-1.2.0

#529 Wrap error if failed to fetch mon
  pkg/cephfs/volumeoptions.go
  pkg/rbd/rbd_util.go
Labels: release-1.2.0

#438 Prometheus liveness probe sidecar
  Gopkg.lock
  cmd/cephcsi.go
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/v1.13/helm/templates/nodeplugin-daemonset.yaml
  deploy/cephfs/kubernetes/v1.13/helm/templates/provisioner-service.yaml
  deploy/cephfs/kubernetes/v1.13/helm/templates/provisioner-statefulset.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin.yaml
  deploy/rbd/kubernetes/v1.13/helm/templates/nodeplugin-daemonset.yaml
  deploy/rbd/kubernetes/v1.13/helm/templates/provisioner-service.yaml
  deploy/rbd/kubernetes/v1.13/helm/templates/provisioner-statefulset.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin.yaml
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  docs/metrics.md
  examples/service-monitor.yaml
  pkg/liveness/liveness.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/golang.org/x/sys/unix/affinity_linux.go
  vendor/golang.org/x/sys/unix/dirent.go
  vendor/k8s.io/utils/trace/trace.go
Labels: release-1.2.0

#561 unmap rbd image if connection timeout.
  pkg/rbd/rbd_attach.go
Labels: Priority-0, bug, release-1.2.0

#551 Fix the vulnarabilities in the image.
  deploy/cephcsi/image/Dockerfile
Labels: Priority-0, release-1.2.0

#558 feat: Adds Ceph logo as icon for Helm charts
  assets/ceph-logo.png
  deploy/cephfs/kubernetes/v1.13/helm/ceph-csi-cephfs/Chart.yaml
  deploy/cephfs/kubernetes/v1.14+/helm/ceph-csi-cephfs/Chart.yaml
  deploy/rbd/kubernetes/v1.13/helm/ceph-csi-rbd/Chart.yaml
  deploy/rbd/kubernetes/v1.14+/helm/ceph-csi-rbd/Chart.yaml
Labels: release-1.2.0

#509 Trace backend volume from pvc
  troubleshooting/tools/requirement.txt
  troubleshooting/tools/tracevol.py
Labels: release-1.2.0

#577 Fix E2E Failure
  e2e/deploy-rook.go
Labels: release-1.2.0

#569 Context logging for cephfs, utils, and csicommon
  pkg/cephfs/cephfs_util.go
  pkg/cephfs/cephuser.go
  pkg/cephfs/controllerserver.go
  pkg/cephfs/fsjournal.go
  pkg/cephfs/mountcache.go
  pkg/cephfs/nodeserver.go
  pkg/cephfs/util.go
  pkg/cephfs/volume.go
  pkg/cephfs/volumemounter.go
  pkg/cephfs/volumeoptions.go
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/nodeserver-default.go
  pkg/rbd/controllerserver.go
  pkg/rbd/rbd_journal.go
  pkg/rbd/rbd_util.go
  pkg/util/cephcmds.go
  pkg/util/log.go
  pkg/util/util.go
  pkg/util/voljournal.go
Labels: release-1.2.0
