Repository ceph/ceph-csi, pull requests merged in 2019-09, with the labels that each got.

#582 e2e: correct log format in execCommandInPod()
  e2e/utils.go
Labels: release-1.2.0

#571 Cephfs: Use ceph kernel client if kernel version >= 4.17
  pkg/cephfs/driver.go
  pkg/cephfs/volumemounter.go
Labels: release-1.2.0

#588 Remove volumemounter flag from cephfs
  cmd/cephcsi.go
  docs/deploy-cephfs.md
  examples/cephfs/storageclass.yaml
  pkg/cephfs/driver.go
  pkg/util/util.go
Labels: release-1.2.0

#576 Add mount option for Cephfs
  docs/deploy-cephfs.md
  examples/cephfs/storageclass.yaml
  pkg/cephfs/volumemounter.go
  pkg/cephfs/volumeoptions.go
Labels: Priority-0, release-1.2.0

#594 Add mount option for Cephfs
  docs/deploy-cephfs.md
  examples/cephfs/storageclass.yaml
  pkg/cephfs/volumemounter.go
  pkg/cephfs/volumeoptions.go
Labels: Priority-0, release-1.2.0

#590 Prepare for v1.2.0
  .travis.yml
  Makefile
  README.md
  deploy.sh
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/v1.13/helm/ceph-csi-cephfs/values.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/v1.14+/helm/ceph-csi-cephfs/values.yaml
  deploy/rbd/ceph-csi-rbd
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin.yaml
  deploy/rbd/kubernetes/v1.13/helm/ceph-csi-rbd/values.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin.yaml
  deploy/rbd/kubernetes/v1.14+/helm/ceph-csi-rbd/values.yaml
  scripts/minikube.sh
Labels: Priority-0, release-1.2.0

#606 update readme for v1.2.0 release
  README.md
Labels: release-1.2.0

#608 Log reqID for each request in context based logging
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  pkg/util/log.go
Labels: release-1.2.1

#616 Change the logic of locking
  pkg/cephfs/controllerserver.go
  pkg/cephfs/driver.go
  pkg/cephfs/nodeserver.go
  pkg/rbd/controllerserver.go
  pkg/rbd/driver.go
  pkg/rbd/nodeserver.go
  pkg/rbd/rbd_util.go
  pkg/util/idlocker.go
  pkg/util/idlocker_test.go
Labels: Priority-0, release-1.2.1

#620 connect to provisioner socket
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
Labels: release-1.2.1

#629 Format RBD volumes with `nodiscard` option.
  e2e/rbd.go
  e2e/utils.go
  pkg/rbd/nodeserver.go
Labels: Priority-0, release-1.2.1

#630 backport use rook v1.1.0 in E2E testing
  scripts/travis-functest.sh
Labels: Backport

#632 Backport: Change the logic of locking
  pkg/cephfs/controllerserver.go
  pkg/cephfs/driver.go
  pkg/cephfs/nodeserver.go
  pkg/rbd/controllerserver.go
  pkg/rbd/driver.go
  pkg/rbd/nodeserver.go
  pkg/rbd/rbd_util.go
  pkg/util/idlocker.go
  pkg/util/idlocker_test.go
Labels: Backport, release-1.2.1

#631 Backport connect to provisioner socket
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
Labels: Backport, release-1.2.1

#637 Push cephcsi 1.2.1 image
  Makefile
  deploy.sh
  scripts/minikube.sh
Labels: release-1.2.1

#638 Update templates for 1.2.1
  README.md
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/v1.13/helm/ceph-csi-cephfs/values.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/v1.14+/helm/ceph-csi-cephfs/values.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin.yaml
  deploy/rbd/kubernetes/v1.13/helm/ceph-csi-rbd/values.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin.yaml
  deploy/rbd/kubernetes/v1.14+/helm/ceph-csi-rbd/values.yaml
Labels: release-1.2.1

#636 Format RBD volumes with `nodiscard` formatting options.
  e2e/rbd.go
  e2e/utils.go
  pkg/rbd/nodeserver.go
Labels: release-1.2.1

#635 Set default FS to "ext4" on RBD device
  examples/rbd/storageclass.yaml
Labels: release-1.2.1

#641 We were defaulting to ext4 at first and then moved toxfs.
  examples/rbd/storageclass.yaml
Labels: release-1.2.1

#647 Add a check for nil secrets
  pkg/util/credentials.go
Labels: backport-to-release-v1.2.0

#648 Remove rootfs from rbd provisioner pod
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
Labels: backport-to-release-v1.2.0

#646 fix: adds the POD_NAMESPACE to the RBD provisioner template
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/templates/provisioner-statefulset.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
Labels: backport-to-release-v1.2.0, release-1.2.2

#657 update mergify for auto merging
  .mergify.yml
Labels: backport-to-release-v1.2.0
