Repository ceph/ceph-csi, pull requests merged in 2020-07, with the labels that each got.

#1194 deploy: Missing quotes
  deploy/cephfs/kubernetes/csi-provisioner-rbac.yaml
Labels: component/deployment

#1202 ci: display a warning when GO_ARCH is not set for image-cephcsi
  deploy/cephcsi/image/Dockerfile
Labels: component/testing, ready-to-merge

#1200 cleanup: address err113 warnings about direct error comparisons
  internal/journal/omap.go
  internal/rbd/rbd_util.go
  internal/util/cephcmds.go
  internal/util/connection.go
Labels: cleanup

#1205 rbd: Add RHEL 8.2 kernel to the list to map images with deep-flatten feature.
  internal/rbd/nodeserver.go
Labels: component/rbd

#1204 cleanup: Reduce cyclomatic complexity of topology_test
  internal/util/topology_test.go
Labels: cleanup, component/testing, ready-to-merge

#1208 build: error out when Podman or Docker is not available
  Makefile
Labels: component/build, ready-to-merge

#1207 util: update unit testing for deep flatten
  internal/util/util_test.go
Labels: component/testing, ready-to-merge

#1210 rbd: check image not found error
  internal/rbd/rbd_journal.go
Labels: component/rbd

#1209 cleanup: use errors.As() for error type checks
  internal/rbd/controllerserver.go
  internal/rbd/rbd_journal.go
  internal/rbd/snapshot.go
Labels: cleanup, component/rbd

#1220 ci: use testCephFS flag to skip cephfs tests
  e2e/cephfs.go
Labels: component/testing

#1226 cleanup: Remove support for Delete and Unmounting v1.1.0 PVC
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  cmd/cephcsi.go
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  internal/cephfs/cephuser.go
  internal/cephfs/controllerserver.go
  internal/cephfs/driver.go
  internal/cephfs/util.go
  internal/cephfs/volume.go
  internal/rbd/controllerserver.go
  internal/rbd/driver.go
  internal/rbd/nodeserver.go
  internal/rbd/nodeserver_test.go
  internal/rbd/rbd_util.go
  internal/rbd/rbd_util_test.go
  internal/util/cachepersister.go
  internal/util/k8s.go
  internal/util/k8scmcache.go
  internal/util/nodecache.go
  internal/util/util.go
Labels: cleanup, release-note-required

#1235 rbd: Return current depth if the image is not found
  internal/rbd/rbd_util.go
Labels: ready-to-merge

#1233 cleanup: replace klog with v2
  internal/rbd/clone.go
Labels: ready-to-merge

#1241 build: Build and push multi architecture images to quay.io
  Makefile
  deploy.sh
Labels: ready-to-merge

#1245 build: Fix docker permission issue during manifest create
  deploy.sh
Labels: ready-to-merge

#1247 cephfs: return volume not found error if volume doesnot exists
  internal/cephfs/volume.go
Labels: ready-to-merge

#1249 doc: add document for rbd snapshot and clone
  docs/design/proposals/rbd-snap-clone.md
Labels: component/docs

#1237 ci: update rook to 1.2.7 to make use of v14.2.10 ceph cluster
  scripts/rook.sh
Labels: component/testing

#1251 rbd: Support data-pool when cloning rbd image
  internal/rbd/rbd_util.go
Labels: component/rbd

#1266 Remove support from Mimic in ceph-csi
  README.md
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
Labels: ready-to-merge

#1268 doc: correct kubernetes version for snap and clone
  README.md
Labels: ready-to-merge

#1270 ci: fix rook cluster version fetching
  scripts/rook.sh
Labels: component/testing

#1257 rbd: disable reflink while creating XFS filesystems
  internal/rbd/nodeserver.go
Labels: bug, component/rbd

#1275 lift kube dependency to v0.18.6
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/apiserver/pkg/storage/errors.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/csi-translation-lib/CONTRIBUTING.md
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/kubelet/types/constants.go
  vendor/k8s.io/kubernetes/pkg/kubelet/types/types.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/noderesources/resource_allocation.go
  vendor/k8s.io/kubernetes/pkg/scheduler/nodeinfo/node_info.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/BUILD
  vendor/k8s.io/kubernetes/pkg/scheduler/util/non_zero.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/test/e2e/framework/.import-restrictions
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: ready-to-merge

#1274 ci: require jjb-validate job to succeed for ci/centos branch
  .mergify.yml
Labels: component/testing, ready-to-merge

#1280 doc: correct upgrade doc
  docs/ceph-csi-upgrade.md
Labels: backport-to-release-v3.0, ready-to-merge

#1282 build: update templates and scripts for 3.0-canary
  Makefile
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy.sh
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: component/build
