Repository ceph/ceph-csi, pull requests merged in 2020-12, with the labels that each got.

#1735 cephfs: fix logic to call ceph fs resize
  internal/cephfs/volume.go
Labels: backport-to-release-v3.1, component/cephfs, ready-to-merge

#1747 ci: update mergify rule for multi arch build
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, component/testing

#1748 ci: log output of "docker image save"
  podman2minikube.sh
Labels: component/testing, ready-to-merge

#1736 helm: make kubelet path configurable
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-psp.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-psp.yaml
  charts/ceph-csi-rbd/values.yaml
Labels: component/deployment, ready-to-merge

#1750 ci: add github action for multiarch build
  .github/workflows/build-multi-stage.yaml
Labels: ci/skip/e2e, component/testing, ready-to-merge

#1751 ci: run github work flow only for pull request
  .github/workflows/build-multi-stage.yaml
  .github/workflows/codespell.yaml
Labels: Repo activity, backport-to-release-v3.1, ci/skip/e2e, component/testing, ready-to-merge

#1546 doc: update snap-clone with rbd snapshot
  docs/snap-clone.md
Labels: ci/skip/e2e, component/cephfs, component/docs, component/rbd, ready-to-merge

#1756 ci: set imagePullPolicy for Vault to IfNotPresent
  examples/kms/vault/vault.yaml
Labels: component/testing, ready-to-merge

#1760 build: install diffutils in test container image
  scripts/Dockerfile.test
Labels: component/build, component/testing, ready-to-merge

#1762 ci: add github workflows for static checks
  .github/workflows/commitlint.yaml
  .github/workflows/go-test.yaml
  .github/workflows/golanci-lint.yaml
  .github/workflows/gosec.yaml
  .github/workflows/lint-extras.yaml
  .github/workflows/mod-check.yaml
  .travis.yml
Labels: Repo activity, ci/skip/e2e, component/testing

#1766 ci: update mergify rules for github actions
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, component/testing

#1767 doc: add upgrade document for 3.2
  docs/ceph-csi-upgrade.md
Labels: ci/skip/e2e, component/docs

#1653 deploy: update csi sidecar images
  charts/ceph-csi-cephfs/templates/provisioner-clusterrole.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/provisioner-clusterrole.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/csi-provisioner-rbac.yaml
  deploy/rbd/kubernetes/csi-provisioner-rbac.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: component/deployment

#1769 ci: add mergify rules for release-v3.2
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, component/testing

#1768 doc: update new release matrix
  README.md
Labels: ci/skip/e2e, component/docs, ready-to-merge

#1776 e2e: fix kubectl_retry to not return a stale error
  scripts/rook.sh
Labels: component/testing, ready-to-merge

#1777 build: update CSI_IMAGE_VERSION in deploy.sh
  deploy.sh
Labels: backport-to-release-v3.2, ci/skip/e2e, component/deployment

#1743 doc: multi-tenancy with Vault tokens
  docs/design/proposals/encryption-with-vault-tokens.md
Labels: ci/skip/e2e, component/docs, enhancement

#1783 doc: add usage for Vault Tokens KMS support
  docs/deploy-rbd.md
Labels: ci/skip/e2e, component/docs, ready-to-merge

#1790 ci: add jobs with Kubernetes v1.20
  jobs/k8s-e2e-external-storage.yaml
  jobs/mini-e2e.yaml
Labels: component/testing, dependency/k8s, ready-to-merge

#1792 ci: detect latest version with "Kubernetes" prefix
  scripts/get_patch_release.py
Labels: component/testing, dependency/k8s, ready-to-merge

#1794 deploy: Fix snapshot controller deployment
  scripts/install-snapshot.sh
Labels: component/deployment, component/testing, ready-to-merge

#1787 util: add support for vault certificates
  docs/design/proposals/encryption-with-vault-tokens.md
  internal/util/crypto.go
  internal/util/vault.go
  internal/util/vault_tokens.go
  internal/util/vault_tokens_test.go
Labels: component/rbd, ready-to-merge

#1788 VaultToken Tenants should be able to (re)configure the connection to the Vault Service
  examples/kms/vault/tenant-config.yaml
  internal/util/vault_tokens.go
Labels: component/rbd, component/util, enhancement, ready-to-merge

#1789 rbd: read configuration from the configmap
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  internal/util/crypto.go
  internal/util/vault_tokens.go
Labels: component/rbd, enhancement, ready-to-merge

#1796 deploy: allow rbd nodeplugin to read ConfigMaps from Tenants
  charts/ceph-csi-rbd/templates/nodeplugin-clusterrole.yaml
  deploy/rbd/kubernetes/csi-nodeplugin-rbac.yaml
Labels: component/deployment, ready-to-merge

#1757 e2e: log events from deployment namespace
  e2e/cephfs.go
  e2e/rbd.go
  e2e/upgrade-cephfs.go
  e2e/upgrade-rbd.go
Labels: component/testing, logging, ready-to-merge

#1805 ci: require ci/centos/mini-e2e/k8s-1.20 for merging
  .mergify.yml
Labels: Repo activity, component/testing

#1806 ci: do not run jobs with Kubernetes v1.18 anymore
  jobs/mini-e2e.yaml
  jobs/upgrade-tests.yaml
Labels: component/testing, ready-to-merge

#1813 build: only use --cpuset options when the cgroup controller is available
  Makefile
Labels: component/build, ready-to-merge
