Repository ceph/ceph-csi, pull requests merged in 2020-09, with the labels that each got.

#1453 ci: add a way to supply CONTAINER_CMD of choice
  scripts/minikube.sh
Labels: component/testing, ready-to-merge

#1378 rebase: update the CSI Spec to v1.3.0
  go.mod
  go.sum
  internal/csi-common/controllerserver-default.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: ready-to-merge, rebase

#1457 ci: update kubernetes version in e2e job
  jobs/mini-e2e.yaml
Labels: component/testing, ready-to-merge

#1452 e2e: rework on E2E framework
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/configmap.go
  e2e/namespace.go
  e2e/node.go
  e2e/pod.go
  e2e/pvc.go
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/resize.go
  e2e/snapshot.go
  e2e/staticpvc.go
  e2e/upgrade-cephfs.go
  e2e/upgrade-rbd.go
  e2e/utils.go
Labels: Priority-0, component/testing, ready-to-merge

#1478 ci: update mergify rules for e2e tests
  .mergify.yml
Labels: Repo activity

#1481 ci: drop Kubernetes patch version from conditions
  .mergify.yml
Labels: Repo activity

#1463 doc: update readme for v3.1.0 and RBD ROX support
  README.md
Labels: ci/skip/e2e, component/docs, ready-to-merge

#1504 ci: Add an escape character before UPGRADE_VERSION
  upgrade-tests.groovy
Labels: component/testing

#1474 fix: Stale bot configuration changes
  .github/stale.yml
Labels: Repo activity

#1495 cephfs: check ENOTEMPTY when removing subvolume
  internal/cephfs/controllerserver.go
  internal/cephfs/errors.go
  internal/cephfs/volume.go
Labels: backport-to-release-v3.1, component/cephfs

#1515 ci: do not install Docker on the minikube host
  single-node-k8s.sh
Labels: component/testing, ready-to-merge

#1517 ci: run minikube.sh with podman
  single-node-k8s.sh
Labels: component/testing, ready-to-merge

#1518 ci: pass REBASE=1 to have commitlint rebase the branch
  ci-job-validation.groovy
Labels: component/testing, ready-to-merge

#1516 ci: do not assume Docker is availble on the minikube host
  scripts/minikube.sh
Labels: backport-to-release-v3.1, component/testing, ready-to-merge

#1514 ci: correct indentation on mini-e2e-helm
  mini-e2e-helm.groovy
Labels: cleanup, component/testing

#1513 ci: trigger upgrade tests job only on phrase
  jobs/upgrade-tests.yaml
Labels: component/testing

#1522 ci: remove old jobs when deploying
  deploy/Makefile
Labels: cleanup, component/testing, ready-to-merge

#1520 ci: do not assume Docker is availble on the minikube host
  scripts/minikube.sh
Labels: Backport, component/testing, ready-to-merge

#1446 rbd: replace cli with go-ceph for snapshot namespace
  internal/rbd/controllerserver.go
  internal/rbd/rbd_util.go
Labels: component/rbd

#1524 ci: update k8s version for upgrade tests
  jobs/upgrade-tests.yaml
Labels: component/testing, ready-to-merge

#1525 cephfs: correct cephFSCloneInprogress source code comment
  internal/cephfs/clone.go
Labels: cleanup, ready-to-merge

#1531 doc: update memory assigned to minikube vm
  e2e/README.md
Labels: ci/skip/e2e, ready-to-merge

#1526 ci: add files to run Kubernetes external storage e2e suite
  scripts/k8s-storage/README.md
  scripts/k8s-storage/create-storageclasses.sh
  scripts/k8s-storage/driver-cephfs.yaml
  scripts/k8s-storage/driver-rbd-rwo.yaml
  scripts/k8s-storage/sc-cephfs.yaml.in
  scripts/k8s-storage/sc-rbd.yaml.in
Labels: component/testing

#1528 build: update templates for v3.1.1 release
  Makefile
  build.env
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy.sh
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  docs/ceph-csi-upgrade.md
  scripts/minikube.sh
Labels: component/build

#1536 added precisions about snapshotting
  docs/cephfs-snap-clone.md
  examples/README.md
Labels: component/docs, ready-to-merge

#1538 Revert "build: update templates for v3.1.1 release"
  Makefile
  build.env
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy.sh
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: component/build
