Repository ceph/ceph-csi, pull requests merged in 2020-01, with the labels that each got.

#772 Upgrade: csi-resizer from v0.3.0 to v0.4.0
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
  scripts/minikube.sh
Labels: release-2.0.0

#771 Remove hard-coded UpdateStrategy from templates
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin.yaml
Labels: release-2.0.0

#769 Upgrade: csi-node-driver-registrar from v1.1.0 to v1.2.0
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: release-2.0.0

#768 Upgrade: csi-snapshotter from v1.2.1 to v1.2.2
  charts/ceph-csi-rbd/values.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
  scripts/minikube.sh
Labels: release-2.0.0

#766 Upgrade: csi-attacher from v1.2.0 to v2.1.0
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-provisioner-rbac.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.14+/csi-provisioner-rbac.yaml
  deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml
  scripts/minikube.sh
Labels: release-2.0.0

#707 Support Arm64 image
  .travis.yml
  Makefile
  README.md
  deploy.sh
  deploy/cephcsi/image/Dockerfile
  scripts/minikube.sh
Labels: release-2.0.0

#759 Add resize doc for both filesystem and block mode PVCs
  docs/resize-pvc.md
Labels: release-2.0.0

#770 Add ceph-csi Upgrade documentation
  docs/ceph-csi-upgrade.md
Labels: Priority-0, release-2.0.0

#787 Rook deploy script, Adding rbd_pool check and cephfilesystem check.
  scripts/minikube.sh
  scripts/rook.sh
Labels: release-2.0.0

#764 Remove Kubernetes 1.13.x support
  .travis.yml
  README.md
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/templates/provisioner-role.yaml
  charts/ceph-csi-cephfs/templates/provisioner-service.yaml
  charts/ceph-csi-cephfs/templates/provisioner-statefulset.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/templates/provisioner-role.yaml
  charts/ceph-csi-rbd/templates/provisioner-rules-clusterrole.yaml
  charts/ceph-csi-rbd/templates/provisioner-service.yaml
  charts/ceph-csi-rbd/templates/provisioner-statefulset.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/csi-config-map.yaml
  deploy/cephfs/kubernetes/csi-nodeplugin-rbac.yaml
  deploy/cephfs/kubernetes/csi-provisioner-rbac.yaml
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/v1.13/csi-provisioner-rbac.yaml
  deploy/cephfs/kubernetes/v1.14+/csi-nodeplugin-rbac.yaml
  deploy/rbd/kubernetes/csi-config-map.yaml
  deploy/rbd/kubernetes/csi-nodeplugin-rbac.yaml
  deploy/rbd/kubernetes/csi-provisioner-rbac.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  deploy/rbd/kubernetes/v1.13/csi-config-map.yaml
  deploy/rbd/kubernetes/v1.13/csi-provisioner-rbac.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/v1.13/csi-rbdplugin.yaml
  deploy/rbd/kubernetes/v1.14+/csi-config-map.yaml
  deploy/rbd/kubernetes/v1.14+/csi-nodeplugin-rbac.yaml
  docs/ceph-csi-upgrade.md
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  e2e/README.md
  e2e/cephfs.go
  e2e/rbd.go
  e2e/utils.go
  examples/README.md
  examples/cephfs/plugin-deploy.sh
  examples/cephfs/plugin-teardown.sh
  examples/rbd/plugin-deploy.sh
  examples/rbd/plugin-teardown.sh
  scripts/minikube.sh
Labels: release-2.0.0

#794 rbd: only load nbd module if not available yet
  pkg/rbd/rbd_attach.go
Labels: rbd, release-2.0.0

#785 Added PodSecurityPolicy support to charts
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-psp.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-role.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-rolebinding.yaml
  charts/ceph-csi-cephfs/templates/provisioner-psp.yaml
  charts/ceph-csi-cephfs/templates/provisioner-role.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-psp.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-role.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-rolebinding.yaml
  charts/ceph-csi-rbd/templates/provisioner-psp.yaml
  charts/ceph-csi-rbd/templates/provisioner-role.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-nodeplugin-psp.yaml
  deploy/cephfs/kubernetes/csi-provisioner-psp.yaml
  deploy/rbd/kubernetes/csi-nodeplugin-psp.yaml
  deploy/rbd/kubernetes/csi-provisioner-psp.yaml
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  e2e/cephfs.go
  e2e/rbd.go
  scripts/minikube.sh
  scripts/psp.yaml
Labels: Release-2.1.0, backport-to-release-v2.0

#813 [Fix rbd chart]Repair typo in host-mount and host-dev definition. It was swithced be…
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
Labels: backport-to-release-v2.0
