Repository ceph/ceph-csi, pull requests merged in 2020-11, with the labels that each got.

#1651 ci: Add the ability to run JJB from private branch/fork
  deploy/jjb-deploy.yaml
  deploy/jjb-validate.yaml
  deploy/jjb.sh
  jobs/jjb-deploy.yaml
  jobs/jjb-validate.yaml
Labels: component/testing, ready-to-merge

#1654 rbd: replace go-ceph GetParentInfo() with GetParent()
  internal/rbd/rbd_util.go
Labels: cleanup, component/rbd, ready-to-merge

#1657 ci: pass BASE_IMAGE to "oc start-build"
  jobs/build-images.yaml
Labels: component/testing, ready-to-merge

#1658 ci: flatten images for internal consumption
  deploy/ceph-csi-buildconfig.yaml
Labels: component/testing, ready-to-merge

#1659 ci: link to the job in the Blue Ocean webui
  jobs/ci-job-validation.yaml
  jobs/commitlint.yaml
  jobs/containerized-tests.yaml
  jobs/jjb-validate.yaml
  jobs/k8s-e2e-external-storage.yaml
  jobs/mini-e2e.yaml
  jobs/upgrade-tests.yaml
Labels: component/testing, ready-to-merge

#1655 ci: allow passing USE_PULLED_IMAGE=yes to use pre-pulled images
  Makefile
Labels: component/build, component/testing, ready-to-merge

#1661 ci: fix Blue Ocean status-url for JJB templates
  jobs/mini-e2e.yaml
  jobs/upgrade-tests.yaml
Labels: component/testing, ready-to-merge

#1662 ci: deploy/jjb.sh should fail on wrong arguments
  deploy/jjb.sh
Labels: component/testing, ready-to-merge

#1666 e2e: do not use Failf() to abort tests in a go-routine
  e2e/cephfs.go
Labels: component/testing, ready-to-merge

#1673 ci: update minikube to latest version
  build.env
Labels: component/testing

#1669 journal: fix reading omaps from objects with large key counts
  internal/journal/omap.go
Labels: backport-to-release-v3.1, component/journal, ready-to-merge

#1668 cephfs: ignore quota when SubVolumeInfo() returns Infinite
  internal/cephfs/volume.go
Labels: bug, component/cephfs

#1679 ci: pull cached images from local registry
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1681 ci: use "podman login --username" instead of "--user"
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1680 ci: use the Fedora container registry for cephcsi:test
  scripts/Dockerfile.test
Labels: component/testing, ready-to-merge

#1683 ci: use podman to login on the CI registry
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1685 ci: correctly fetch BASE_IMAGE from build.env
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1684 ci: do not run commitlint on "/retest all"
  jobs/commitlint.yaml
Labels: component/testing, ready-to-merge

#1686 ci: escape command to be executed over ssh to fetch BASE_IMAGE
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1687 ci: store results of podman-login in ~/.docker/config.json
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1688 ci: store podman-login results in ~/.podman-auth.json
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1689 ci: the image in the CI registry is called "ceph-csi"
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1690 cephfs: check only the stderror message for umount
  internal/cephfs/volumemounter.go
Labels: component/cephfs

#1678 rbd: add minsnapshotsonimage flag
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
  cmd/cephcsi.go
  internal/rbd/controllerserver.go
  internal/rbd/driver.go
  internal/util/util.go
  scripts/install-helm.sh
Labels: backport-to-release-v3.1, component/rbd

#1701 ci: fix calling podman_login()
  containerized-tests.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1703 ci: pass registry to podman helper functions
  containerized-tests.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1696 e2e: set imagePullPolicy to ifNotPresent
  e2e/pod.go
Labels: backport-to-release-v3.1, ready-to-merge

#1698 rbd: add minsnapshotsonimage flag
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
  cmd/cephcsi.go
  internal/rbd/controllerserver.go
  internal/rbd/driver.go
  internal/util/util.go
  scripts/install-helm.sh
Labels: component/rbd

#1707 build: update templates for v3.1.2 release
  Makefile
  build.env
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy.sh
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  docs/ceph-csi-upgrade.md
  scripts/minikube.sh
Labels: component/deployment

#1711 ci: pre-pull rook/ceph image from local registry
  mini-e2e-helm.groovy
  mini-e2e.groovy
  single-node-k8s.sh
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1712 build: add ROOK_VERSION to build.env
  build.env
Labels: component/build, component/testing, ready-to-merge

#1715 deploy: use docker.io for unqualified image names
  examples/README.md
  examples/cephfs/deployment.yaml
  examples/cephfs/pod-clone.yaml
  examples/cephfs/pod-restore.yaml
  examples/cephfs/pod.yaml
  examples/kms/vault/vault.yaml
  examples/rbd/pod-clone.yaml
  examples/rbd/pod-restore.yaml
  examples/rbd/pod.yaml
Labels: component/deployment, component/testing, ready-to-merge

#1716 ci: gather logs when deploying Rook fails
  scripts/rook.sh
Labels: component/deployment, component/testing, dependency/rook

#1719 ci: add more logging during Rook deployment
  scripts/rook.sh
Labels: component/testing, ready-to-merge

#1723 ci: strip localhost/ prefix after importing images in minikube
  podman2minikube.sh
Labels: component/testing, ready-to-merge

#1720 ci: do not mark script changes as doc-only
  scripts/skip-doc-change.sh
Labels: component/testing, ready-to-merge

#1724 ci: push ceph/ceph container image into minikube
  single-node-k8s.sh
Labels: component/testing, ready-to-merge

#1729 ci: use docker.io/library/ as prefix for nginx and vault images
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1730 e2e: use docker.io/library as prefix for official images
  examples/README.md
  examples/cephfs/deployment.yaml
  examples/cephfs/pod-clone.yaml
  examples/cephfs/pod-restore.yaml
  examples/cephfs/pod.yaml
  examples/kms/vault/vault.yaml
  examples/rbd/pod-clone.yaml
  examples/rbd/pod-restore.yaml
  examples/rbd/pod.yaml
Labels: component/testing, ready-to-merge

#1644 cephfs: replace getCloneInfo() with a go-ceph implementation
  internal/cephfs/clone.go
  internal/cephfs/fsjournal.go
Labels: component/cephfs, enhancement

#1621 doc: design document for rbd mirroring
  docs/design/proposals/rbd-mirror.md
  docs/design/proposals/rbd-mirror.png
Labels: component/docs, component/rbd, ready-to-merge

#1738 ci: pull BASE_IMAGE from local registry
  containerized-tests.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1737 build: use docker.io/ceph/ceph:v15 as BASE_IMAGE
  build.env
Labels: component/build, component/testing, ready-to-merge

#1740 e2e: use full-qualified-image-name for vault-init-job
  examples/kms/vault/vault.yaml
Labels: component/testing, ready-to-merge

#1741 rebase: split vaultConnection from VaultKMS
  internal/util/vault.go
Labels: component/util, ready-to-merge, rebase
