Repository ceph/ceph-csi, pull requests merged in 2020-04, with the labels that each got.

#905 Upgrade: csi-node-driver-registrar from v1.2.0 to v1.3.0
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: Release-2.1.0

#900 Log error message for cephfs
  pkg/cephfs/volumemounter.go
Labels: Release-2.1.0, backport-to-release-v2.0

#888 Deprecate grpc metrics in ceph-csi
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-grpc-service.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/templates/provisioner-grpc-service.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-grpc-service.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/templates/provisioner-grpc-service.yaml
  charts/ceph-csi-rbd/values.yaml
  cmd/cephcsi.go
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  docs/metrics.md
  examples/service-monitor.yaml
  pkg/cephfs/driver.go
  pkg/rbd/driver.go
Labels: Release-2.1.0

#907 Move cephfs support from alpha to beta
  README.md
Labels: Release-2.1.0

#894 tests: in case 'go test' is run in a container, skip TestGetPIDLimit()
  .travis.yml
  docs/development-guide.md
  pkg/util/pidlimit_test.go
Labels: Release-2.1.0

#916 Resizer: Update resizer image version
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  scripts/minikube.sh
Labels: Release-2.1.0

#922 Cleanup vendor dependencies.
  go.mod
  go.sum
  vendor/modules.txt
Labels: Release-2.1.0

#875 util/cephcmds: have GetOMapValue() return ErrPoolNotFound
  pkg/util/cephcmds.go
  pkg/util/voljournal.go
Labels: backport-to-release-v2.0, bug

#918 Update golang to 1.13.9
  scripts/Dockerfile.devel
Labels: Release-2.1.0

#910 Document about stale resource cleanup
  README.md
  docs/resource-cleanup.md
Labels: Release-2.1.0

#942 Support externally managed configmap.
  charts/ceph-csi-cephfs/templates/csiplugin-configmap.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/csiplugin-configmap.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
Labels: Release-2.1.0, backport-to-release-v2.1

#939 Upgrade: Upgrade doc for v2.1.0
  docs/ceph-csi-upgrade.md
Labels: backport-to-release-v2.1

#954 doc: update to current release tracking method
  docs/releases.md
Labels: documentation

#956 travis: split static checks and continue with tests in case one fails
  .travis.yml
  Makefile
Labels: cleanup, testing

#797 util: use MiB and GiB constants from k8s helpers
  pkg/rbd/rbd_util.go
  pkg/util/util.go
Labels: cleanup

#967 doc: add description for containerized-test to development-guide
  docs/development-guide.md
Labels: documentation, testing

#965 travis: group build/e2e testing in stages
  .travis.yml
Labels: testing

#962 Cleanup the containerized-build Dockerfile
  Makefile
  scripts/Dockerfile.devel
Labels: cleanup

#972 Add support to build multi architecture image
  .travis.yml
  Makefile
  build-multi-arch-image.sh
  deploy.sh
  deploy/cephcsi/image/Dockerfile
Labels: testing

#971 Add travis_wait to deploy section
  .travis.yml
Labels: Priority-0, testing

#976 Add grpc 1.27 version require section in go.mod to avoid CI issue
  go.mod
Labels: backport-to-release-v2.1

#977 e2e: fix IneffAssign warnings in checkPVSelectorValuesForPVC()
  e2e/utils.go
Labels: cleanup, testing

#964 add optional TARGET=.. parameter for 'make containerized-test'
  Makefile
Labels: testing

#985 use temp folder to push helm charts
  deploy.sh
Labels: component/testing

#993 travis: run deploy as final stage
  .travis.yml
Labels: Repo activity, cleanup, component/testing

#995 util: fix golint warnings in csiconfig, volid
  internal/util/csiconfig.go
  internal/util/volid.go
Labels: cleanup
