Repository ceph/ceph-csi, pull requests merged in 2020-10, with the labels that each got.

#1530 ci: Trigger upgrade test jobs automatically
  jobs/upgrade-tests.yaml
Labels: component/testing

#1529 ci: require upgrade tests to pass for merging
  .mergify.yml
Labels: Repo activity

#1548 cleanup: standardize error logs in cephfs/volume.go
  internal/cephfs/volume.go
Labels: cleanup, component/cephfs, logging

#1561 doc: update encryption doc for rbd
  docs/deploy-rbd.md
Labels: ci/skip/e2e, component/docs, ready-to-merge

#1565 rbd: make sure csi rbd pv encryption defaulting to luks2 version
  docs/design/proposals/encrypted-pvc.md
  internal/util/cryptsetup.go
Labels: component/rbd, enhancement, rebase

#1567 rbd: correct typo in validateRequestedVolumeSize()
  internal/rbd/controllerserver.go
Labels: ready-to-merge

#1573 e2e: add snapshotter deploy functionality to minikube script
  scripts/minikube.sh
Labels: component/testing

#1575 rebase: update vendored go-ceph to v0.6
  go.mod
  go.sum
  vendor/github.com/ceph/go-ceph/internal/callbacks/callbacks.go
  vendor/github.com/ceph/go-ceph/internal/cutil/cutil.go
  vendor/github.com/ceph/go-ceph/internal/cutil/iovec.go
  vendor/github.com/ceph/go-ceph/rbd/diff_iterate.go
  vendor/github.com/ceph/go-ceph/rbd/rbd_nautilus.go
  vendor/github.com/ceph/go-ceph/rbd/snapshot.go
  vendor/github.com/ceph/go-ceph/rbd/snapshot_nautilus.go
  vendor/github.com/ceph/go-ceph/rbd/snapshot_octopus.go
  vendor/github.com/ceph/go-ceph/rbd/watchers_mimic.go
  vendor/modules.txt
Labels: rebase

#1534 e2e: defend on k8s version for snap-controller install
  build.env
  scripts/install-snapshot.sh
Labels: component/testing, enhancement

#1570 doc: add install-snapshot.sh usage in snapshot documentation
  docs/cephfs-snap-clone.md
Labels: component/deployment, component/docs

#1584 rbd: remove unwanted condition check in flattenCloneImage
  internal/rbd/clone.go
Labels: cleanup, component/rbd

#1585 rbd: remove unused credentials argument from StoreImageID()
  internal/journal/voljournal.go
  internal/rbd/clone.go
  internal/rbd/controllerserver.go
  internal/rbd/rbd_journal.go
  internal/rbd/rbd_util.go
Labels: cleanup, component/journal

#1587 ci: set GITHUB_API_TOKEN in the environment for all stages
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1590 ci: use Kubernetes 1.19.2 to merge PRs
  .mergify.yml
Labels: Repo activity

#1577 cephfs: implement getFscID() with go-ceph
  internal/cephfs/cephfs_util.go
  internal/cephfs/volumeoptions.go
Labels: component/cephfs, enhancement

#1581 cephfs: implement getFsName() with go-ceph
  internal/cephfs/cephfs_util.go
  internal/cephfs/volumeoptions.go
Labels: component/cephfs, enhancement

#1596 ci: use Kubernetes 1.18.9 for CI jobs
  jobs/mini-e2e.yaml
  jobs/upgrade-tests.yaml
Labels: component/testing, ready-to-merge

#1597 ci: update mergify rules for E2E on kubernetes 1.18.9
  .mergify.yml
Labels: Repo activity

#1602 ci: get the GitHub API Token before starting a node
  mini-e2e-helm.groovy
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1603 Update mergify rules to auto merging
  .mergify.yml
Labels: Repo activity

#1604 ci: use the credentials-binding plugin for the GitHub API Token
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1600 cephfs: replace with a different variable name for builtin `cap` attribute
  internal/cephfs/controllerserver.go
  internal/cephfs/util.go
  internal/csi-common/driver.go
Labels: cleanup, component/cephfs

#1601 cephfs: fix wrong error check in CreateVolume rollback action
  internal/cephfs/controllerserver.go
Labels: backport-to-release-v3.1, component/cephfs

#1609 ci: move skip-e2e-check after GitHub API usage
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing

#1606 rbd: correct the code comment for ErrFlattenInProgress
  internal/rbd/errors.go
Labels: ci/skip/e2e, cleanup, component/rbd

#1605 rbd: volJournal.Connect() error return wrongly pushed to caller
  internal/rbd/nodeserver.go
Labels: component/rbd

#1610 helm: make log level configurable
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
Labels: component/deployment

#1595 util: remove unused CSI server initialization functions
  internal/csi-common/utils.go
Labels: cleanup

#1617 ci: use refs/pull/<id>/merge to prevent need for rebases
  commitlint.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1611 e2e: validate the error return instead of object for consistency
  e2e/cephfs.go
  e2e/resize.go
  e2e/upgrade-cephfs.go
  e2e/upgrade-rbd.go
  e2e/utils.go
Labels: cleanup, component/testing, ready-to-merge

#1618 util: NewCredentials() dont have any callers
  internal/util/credentials.go
Labels: cleanup, component/util

#1615 doc: update developer guide about retriggering CI jobs
  docs/development-guide.md
Labels: component/docs

#1614 ci: improve rules for commitlint
  .commitlintrc.yml
Labels: Repo activity

#1623 doc: remove the description of provisioner statefulset
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
Labels: ci/skip/e2e, ready-to-merge

#1624 ci: run only one jjb-validate at the time
  jobs/jjb-validate.yaml
Labels: component/testing, ready-to-merge

#1612 cephfs: implement getSubVolumeInfo() with go-ceph
  internal/cephfs/controllerserver.go
  internal/cephfs/volume.go
  internal/cephfs/volumeoptions.go
Labels: component/cephfs, enhancement

#1622 ci: create ceph-csi-config ConfigMap for external storage tests
  scripts/k8s-storage/README.md
  scripts/k8s-storage/create-configmap.sh
Labels: component/testing, ready-to-merge

#1627 ci: copy run-k8s-external-storage-e2e.sh to bare-metal machine
  k8s-e2e-external-storage.groovy
Labels: component/testing, ready-to-merge

#1633 rebase: update minikube to v1.14.1
  build.env
Labels: component/testing, ready-to-merge, rebase

#1640 ci: Fix shellcheck warnings for prepare.sh
  prepare.sh
Labels: cleanup, component/testing

#1638 ci: use major Kubernetes versions again
  jobs/k8s-e2e-external-storage.yaml
  jobs/mini-e2e.yaml
  jobs/upgrade-tests.yaml
Labels: component/testing, ready-to-merge

#1639 ci: use major Kubernetes versions again for Mergify checks
  .mergify.yml
Labels: Repo activity, component/testing

#1635 ci: fix shellcheck in test-go
  scripts/test-go.sh
Labels: component/testing, ready-to-merge

#1631 build: install git as when building from Dockerfile
  deploy/cephcsi/image/Dockerfile
Labels: component/build, component/deployment, ready-to-merge

#1630 ci: use github/refs/pull/<pr-id>/merge instead of doing a rebase
  ci-job-validation.groovy
  containerized-tests.groovy
  jobs/jjb-validate.yaml
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1626 e2e: retry deploying on API-server timeouts
  e2e/pod.go
Labels: component/testing, ready-to-merge

#1616 cephfs: implement resizeVolume() with go-ceph
  internal/cephfs/clone.go
  internal/cephfs/controllerserver.go
  internal/cephfs/volume.go
Labels: component/cephfs, enhancement, ready-to-merge

#1632 Do not Go panic on missing or wrong arguments to the executable
  cmd/cephcsi.go
Labels: cleanup, logging, ready-to-merge

#1643 ci: use self-contained kubeconfig for running k8s e2e job
  run-k8s-external-storage-e2e.sh
Labels: component/testing, ready-to-merge
