Repository ceph/ceph-csi, pull requests merged in 2020-06, with the labels that each got.

#1117 rbd: Add new methods to generate spec strings
  internal/rbd/controllerserver.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_attach.go
  internal/rbd/rbd_util.go
Labels: cleanup, component/rbd

#1113 build: add option to compile e2e.test in a container
  .gitignore
  Makefile
Labels: component/testing, ready-to-merge

#1125 util: remove unused GetImageMeta() and SetImageMeta()
  internal/util/cephcmds.go
Labels: cleanup, component/rbd, component/util, ready-to-merge

#1128 ci: pass target filename of /etc/resolv.conf in case it is a symlink
  scripts/minikube.sh
Labels: component/testing, ready-to-merge

#1129 rbd: keep rados.IOContext for re-use
  internal/rbd/rbd_util.go
Labels: component/rbd

#1126 util: implement CreateObject() and RemoveObject with go-ceph
  internal/util/cephcmds.go
Labels: cleanup, component/util

#1141 build: add check for ceph development headers
  scripts/check-env.sh
Labels: component/build

#1151 doc: make sure configmap object referred or documented correctly
  docs/deploy-rbd.md
  docs/design/proposals/encrypted-pvc.md
  e2e/deploy-vault.go
  examples/README.md
  examples/cephfs/storageclass.yaml
  examples/csi-config-map-sample.yaml
  examples/rbd/snapshotclass.yaml
  examples/rbd/storageclass.yaml
Labels: cleanup, component/docs, ready-to-merge

#1154 doc: Add v2.1.2 release details to release table
  .travis.yml
  README.md
Labels: component/docs, ready-to-merge

#1163 cleanup: remove double import of csi spec from nodeserver
  internal/csi-common/nodeserver-default.go
Labels: cleanup

#1159 doc: Correct PVC mention in the deployment doc
  docs/deploy-rbd.md
Labels: component/docs, ready-to-merge

#1156 doc: correct PVC expansion documentation
  README.md
  docs/expand-pvc.md
Labels: component/docs

#1172 scripts: add -mod=vendor to go run in check-env.sh
  scripts/check-env.sh
Labels: ready-to-merge

#1177 e2e: Remove arm64 build test from CI
  .travis.yml
Labels: component/testing, ready-to-merge

#1114 cephfs: enhance tracevol.py script to work with cephfs
  troubleshooting/tools/requirement.txt
  troubleshooting/tools/tracevol.py
Labels: component/cephfs, enhancement, ready-to-merge

#1165 cleanup: avoid double import of kubernetes library in e2e utils
  e2e/utils.go
Labels: cleanup

#1179 doc: update coding doc to correct import order
  docs/coding.md
Labels: component/docs, ready-to-merge

#1175 cephfs: Add support for multiple subvolumegroups
  e2e/cephfs.go
  e2e/utils.go
  internal/cephfs/volume.go
Labels: component/cephfs, enhancement

#1186 ci: add pylint as part of CI
  .travis.yml
  Makefile
  scripts/Dockerfile.test
  scripts/lint-extras.sh
Labels: component/testing

#1192 Cleanup messages related to Travis CI configuration
  .travis.yml
Labels: cleanup, component/testing, ready-to-merge
