Repository ceph/ceph-csi, pull requests merged in 2020-08, with the labels that each got.

#1299 ci: use CentOS-8 bare-metal systems for testing
  ci-job-validation.groovy
  containerized-tests.groovy
Labels: cleanup, component/testing

#1300 ci: install make in centos ci
  prepare.sh
Labels: component/testing, ready-to-merge

#1287 util: fix tracevol.py to use namespace argument
  troubleshooting/tools/tracevol.py
Labels: ready-to-merge

#1303 ci: use ci/centos/mini-e2e/k8s-1.18 as context for mini-e2e job
  jobs/mini-e2e.yaml
Labels: component/testing, ready-to-merge

#1304 ci: disable debug sleep on failure of mini-e2e
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1297 rbd: implement rbdVolume.resize() with go-ceph
  internal/rbd/controllerserver.go
  internal/rbd/rbd_util.go
Labels: component/rbd

#1306 ci: use ceph-csi:ci/centos for fetching job scripts
  mini-e2e.groovy
Labels: cleanup, component/testing, ready-to-merge

#1307 ci: pass Kubernetes version as parameter to mini-e2e job
  jobs/mini-e2e.yaml
  mini-e2e.groovy
Labels: component/testing, ready-to-merge

#1295 rbd: return error if fetching cluster id fails
  internal/rbd/controllerserver.go
  internal/rbd/rbd_util.go
Labels: component/rbd

#1309 ci: jjb-deploy should have a "deployment" stage
  jobs/jjb-deploy.yaml
Labels: cleanup, component/testing, ready-to-merge

#1310 ci: use double quotes for variables
  mini-e2e.groovy
Labels: ready-to-merge

#1311 ci: Correct the stage name
  mini-e2e.groovy
Labels: ready-to-merge

#1313 ci: give minikube 8GB RAM on CentOS bare-metal systems
  single-node-k8s.sh
Labels: component/testing, ready-to-merge

#1312 ci: make number of CPUs for minikube VM configurable
  scripts/minikube.sh
Labels: component/testing, ready-to-merge

#1315 ci: add mini-e2e-helm Jenkins job
  jobs/mini-e2e.yaml
  mini-e2e-helm.groovy
Labels: component/testing

#1318 ci: add missing " in mini-e2e-helm script
  mini-e2e-helm.groovy
Labels: bug, component/testing, ready-to-merge

#1320 ci: fix namespace variable
  mini-e2e-helm.groovy
Labels: ready-to-merge

#1321 ci: create test namespace before "helm install ceph-csi"
  mini-e2e-helm.groovy
Labels: bug, component/testing, ready-to-merge

#1322 ci: pass strings with quotes over ssh in mini-e2e-helm
  mini-e2e-helm.groovy
Labels: component/testing

#1327 deploy: add wrapper function of kubectl
  scripts/rook.sh
Labels: component/testing, ready-to-merge

#1335 ci: add commitlint fallback job
  commitlint.groovy
  jobs/commitlint.yaml
Labels: component/testing, ready-to-merge

#1329 rbd: add stagingpath to error message
  internal/util/validate.go
Labels: component/rbd, ready-to-merge

#1345 ci: always fetch GIT_SINCE for commitlint
  Makefile
Labels: component/testing, ready-to-merge

#1346 ci: make members of the GitHub "ceph" organization admins
  jobs/ci-job-validation.yaml
  jobs/commitlint.yaml
  jobs/containerized-tests.yaml
  jobs/jjb-validate.yaml
  jobs/mini-e2e.yaml
Labels: cleanup, component/testing, ready-to-merge

#1347 ci: allow everyone to run the "commitlint" job
  jobs/commitlint.yaml
Labels: component/testing, ready-to-merge

#1351 e2e: update cephcsi upgrade testing version
  .travis.yml
  build.env
Labels: component/testing, rebase

#1339 doc: correct rbd snap-clone doc
  docs/design/proposals/rbd-snap-clone.md
Labels: component/docs, ready-to-merge

#1341 doc: update e2e README for snapshot operation
  e2e/README.md
Labels: component/docs, ready-to-merge

#1349 cephfs: change the volumetype to RWX instead of RWO
  examples/cephfs/pvc-clone.yaml
  examples/cephfs/pvc-restore.yaml
Labels: component/cephfs, component/testing

#1372 ci: use last "git fetch" output to test commitlint
  Makefile
Labels: component/testing, ready-to-merge

#1343 cephfs: Add documentation about snapshot create/restore and clone
  docs/cephfs-snap-clone.md
Labels: component/cephfs, component/docs

#1314 rbd: discard flattening error if the image doesnt have parent
  internal/rbd/rbd_util.go
Labels: component/rbd, ready-to-merge

#1354 doc: update cephfs snapshot, restore and clone support matrix
  README.md
Labels: component/cephfs, component/docs, ready-to-merge

#1363 doc: add upgrade documentation for v3.1.0
  docs/ceph-csi-upgrade.md
Labels: component/docs, ready-to-merge

#1373 doc: add note for cephfs snapshot limitation
  docs/cephfs-snap-clone.md
Labels: ready-to-merge

#1375 ci: the ci-job-validation script uses an undefined variable
  ci-job-validation.groovy
Labels: bug, component/testing

#1374 ci: use build.env:CSI_IMAGE_VERSION for mini-e2e jobs
  single-node-k8s.sh
Labels: component/testing, ready-to-merge

#1350 ci: only retry "kubectl create" if objects are missing
  scripts/rook.sh
Labels: component/deployment, component/testing, ready-to-merge

#1362 ci: add mergify rules for release-v3.1 branch
  .mergify.yml
Labels: Repo activity, component/testing

#1355 ci: use ceph-csi-bot account for merging PRs
  .mergify.yml
Labels: Repo activity

#1332 rebase: use Rook v1.3.9 for mini-e2e jobs
  single-node-k8s.sh
Labels: component/testing, ready-to-merge, rebase

#1385 ci: use GitHub Hooks to trigger jobs
  jobs/ci-job-validation.yaml
  jobs/commitlint.yaml
  jobs/containerized-tests.yaml
  jobs/jjb-validate.yaml
  jobs/mini-e2e.yaml
Labels: component/testing, ready-to-merge

#1278 Documents the capabilities a id require against a ceph cluster
  docs/capabilities.md
Labels: component/docs, ready-to-merge

#1365 ci: prevent Mergify from doing merge commits
  .mergify.yml
Labels: Repo activity, component/testing

#1399 ci: prepare.sh should accept --history without argument
  prepare.sh
Labels: bug, component/testing, ready-to-merge

#1400 cleanup: fix command in the error msg
  deploy/cephcsi/image/Dockerfile
Labels: cleanup, component/deployment, ready-to-merge

#1405 ci: do not require commitlint before merging
  .mergify.yml
Labels: Repo activity, backport-to-release-v2.1, backport-to-release-v3.1, component/testing, ready-to-merge

#1371 deploy: remove unnecessary aggregate clusterroles
  charts/ceph-csi-cephfs/templates/nodeplugin-clusterrole.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-rules-clusterrole.yaml
  charts/ceph-csi-cephfs/templates/provisioner-clusterrole.yaml
  charts/ceph-csi-cephfs/templates/provisioner-rules-clusterrole.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-clusterrole.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-rules-clusterrole.yaml
  charts/ceph-csi-rbd/templates/provisioner-clusterrole.yaml
  charts/ceph-csi-rbd/templates/provisioner-rules-clusterrole.yaml
  deploy/cephfs/kubernetes/csi-nodeplugin-rbac.yaml
  deploy/cephfs/kubernetes/csi-provisioner-rbac.yaml
  deploy/rbd/kubernetes/csi-nodeplugin-rbac.yaml
  deploy/rbd/kubernetes/csi-provisioner-rbac.yaml
Labels: component/deployment, ready-to-merge

#1404 ci: mark .commitlintrc.yml as doc-only
  scripts/skip-doc-change.sh
Labels: component/testing, ready-to-merge

#1403 ci: error out for invalid component in commit header
  .commitlintrc.yml
Labels: component/testing, ready-to-merge

#1402 build: change default to use podman
  Makefile
Labels: component/build

#1386 rbd: Bail out from nodeexpansion if its block mode pvc
  internal/rbd/controllerserver.go
  internal/rbd/nodeserver.go
Labels: backport-to-release-v3.1, bug, component/rbd

#1383 cephfs: use string const for cli error comparison
  internal/cephfs/errors.go
  internal/cephfs/snapshot.go
  internal/cephfs/volume.go
Labels: backport-to-release-v3.1, component/cephfs, ready-to-merge

#1415 ci: skip functional tests for pre-commit config
  scripts/skip-doc-change.sh
Labels: ready-to-merge

#1417 ci: change snapshotter default version to v2.1.1
  scripts/install-snapshot.sh
Labels: backport-to-release-v3.0, backport-to-release-v3.1, ready-to-merge

#1420 doc: Add missing keyword in static-pvc doc
  docs/static-pvc.md
Labels: component/docs, ready-to-merge

#1382 rebase: update golang version to v.1.15
  build.env
Labels: component/testing, rebase

#1401 ci: fix the minikube version check failure
  scripts/minikube.sh
Labels: component/testing

#1360 rebase: update go-ceph to v0.5.0
  go.mod
  go.sum
  vendor/github.com/ceph/go-ceph/internal/cutil/splitbuf.go
  vendor/github.com/ceph/go-ceph/internal/errutil/strerror.go
  vendor/github.com/ceph/go-ceph/internal/timespec/timespec.go
  vendor/github.com/ceph/go-ceph/rados/conn.go
  vendor/github.com/ceph/go-ceph/rados/errors.go
  vendor/github.com/ceph/go-ceph/rados/ioctx.go
  vendor/github.com/ceph/go-ceph/rados/snapshot.go
  vendor/github.com/ceph/go-ceph/rbd/callback_shims.go
  vendor/github.com/ceph/go-ceph/rbd/diff_iterate.go
  vendor/github.com/ceph/go-ceph/rbd/errors.go
  vendor/github.com/ceph/go-ceph/rbd/features.go
  vendor/github.com/ceph/go-ceph/rbd/namespace_nautilus.go
  vendor/github.com/ceph/go-ceph/rbd/options_mimic.go
  vendor/github.com/ceph/go-ceph/rbd/options_nautilus.go
  vendor/github.com/ceph/go-ceph/rbd/pool_nautilus.go
  vendor/github.com/ceph/go-ceph/rbd/rbd.go
  vendor/github.com/ceph/go-ceph/rbd/rbd_mimic.go
  vendor/github.com/ceph/go-ceph/rbd/rbd_nautilus.go
  vendor/github.com/ceph/go-ceph/rbd/snapshot.go
  vendor/github.com/ceph/go-ceph/rbd/snapshot_mimic.go
  vendor/github.com/ceph/go-ceph/rbd/snapshot_namespace.go
  vendor/github.com/ceph/go-ceph/rbd/snapshot_nautilus.go
  vendor/github.com/ceph/go-ceph/rbd/watchers_mimic.go
  vendor/modules.txt
Labels: backport-to-release-v3.1, dependency/go-ceph, rebase

#1298 deploy: update the default configmap value of helm chart
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
Labels: component/deployment, component/docs

#1434 deploy: add missing " for nodes watch verb
  charts/ceph-csi-cephfs/templates/provisioner-clusterrole.yaml
Labels: component/deployment, ready-to-merge

#1432 rbd: implement rbd.updateVolWithImageInfo() with go-ceph
  internal/rbd/rbd_util.go
Labels: backport-to-release-v3.1, component/rbd, enhancement

#1376 util: Fix tracevol to use --config for oc only
  troubleshooting/tools/tracevol.py
Labels: ci/skip/e2e, component/util, ready-to-merge

#1440 doc: add description of most useful GitHub labels
  docs/development-guide.md
Labels: ci/skip/e2e, component/docs

#1426 rbd: use staging path for resize when available
  internal/rbd/nodeserver.go
Labels: backport-to-release-v3.0, backport-to-release-v3.1, component/rbd

#1445 doc: correct default kube version
  e2e/README.md
Labels: ready-to-merge

#1429 deploy: remove preStop hook from daemonset templates
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/deployment, ready-to-merge
