Repository ceph/ceph-csi, pull requests merged in 2020-05, with the labels that each got.

#931 Make CephFS SubvolumeGroup configurable
  charts/ceph-csi-cephfs/values.yaml
  e2e/utils.go
  examples/csi-config-map-sample.yaml
  internal/cephfs/volume.go
  internal/cephfs/volumeoptions.go
  internal/util/csiconfig.go
Labels: component/cephfs, enhancement

#1004 Revert back the ceph base image
  deploy/cephcsi/image/Dockerfile
Labels: bug, component/deployment

#999 travis: group build/e2e testing in stages
  .travis.yml
Labels: Backport, component/testing

#1009 rbd: default nouuid if the formattype is xfs
  internal/rbd/nodeserver.go
Labels: backport-to-release-v2.1, component/rbd

#1007 Prepare for v2.1.1 release
  Makefile
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy.sh
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: Repo activity

#1008 Doc: update development documentation
  docs/development-guide.md
Labels: component/docs

#994 README: Update dev standup meeting details
  README.md
Labels: component/docs

#997 Update Prepare.sh in centos ci branch
  prepare.sh
Labels: component/testing

#862 rbd: implement deleteImage() with go-ceph
  internal/rbd/rbd_util.go
Labels: component/rbd, enhancement

#1014 Update github issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Repo activity, component/docs

#1017 CI: update mergify rules
  .mergify.yml
Labels: Repo activity, component/testing

#1020 prepare: exit when passed incorrect parameters
  prepare.sh
Labels: component/testing

#1021 ci: add initial configuration for stale bot
  .github/stale.yaml
Labels: Repo activity, component/testing, release requirement

#1026 ci: add configuration for "Semantic Pull Request" bot
  .github/semantic.yaml
Labels: Repo activity, component/testing

#1029 ci: check for empty ghprbPullId
  make-containerized-build.groovy
Labels: component/testing

#1037 ci: pass ghprPullId in make-containerized-build job
  make-containerized-build.yaml
Labels: component/testing

#1024 Remove testing of unmaintained k8s versions
  .travis.yml
Labels: cleanup, component/testing

#1018 cephfs: use new 'ceph fs resize' command when available
  internal/cephfs/controllerserver.go
  internal/cephfs/volume.go
Labels: backport-to-release-v2.1, component/cephfs

#1039 journal: remove SetCSIDirectorySuffix to simplify journal creation
  internal/cephfs/driver.go
  internal/journal/voljournal.go
  internal/rbd/driver.go
Labels: cleanup

#1044 cephfs: use new 'ceph fs resize' command when available
  pkg/cephfs/controllerserver.go
  pkg/cephfs/volume.go
Labels: Backport, component/cephfs

#1005 build: add check for functional environment
  Makefile
  scripts/check-env.sh
Labels: component/testing, enhancement

#1053 Disable semantic bot from the repo
  .github/semantic.yaml
Labels: Repo activity

#1036 doc: add list of valid components to the development guide
  docs/development-guide.md
Labels: component/docs

#1032 cleanup: use switch/case for genVolFromVolID() error checking
  internal/rbd/controllerserver.go
Labels: cleanup

#1056 util: make util.ClusterInfo usable outside util package
  e2e/utils.go
  internal/cephfs/volumeoptions.go
  internal/util/csiconfig.go
Labels: cleanup, component/cephfs

#1074 ci: execute build and test stages in parallel
  containerized-tests.groovy
Labels: component/testing, enhancement

#1081 ci: retry if no machine is immediately available
  containerized-tests.groovy
Labels: component/testing

#1080 build: prevent error message when 'go' is unavailable
  Makefile
Labels: cleanup, component/testing

#1064 ci: Add Rule to auto merge the PR based on label and >=1 approval
  .mergify.yml
  docs/development-guide.md
Labels: Repo activity

#1075 doc: update helm documentation
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-rbd/README.md
Labels: component/deployment, component/docs

#1061 ci: Add mergify rules
  .mergify.yml
Labels: component/testing

#1091 ci: Enable stale bot on issues.
  .github/stale.yaml
Labels: ci, component/testing, ready-to-merge

#1100 ci: use parameters set by github-pull-request-builder
  containerized-tests.groovy
  containerized-tests.yaml
Labels: cleanup, component/testing

#1090 doc: Add prefix for naming volume and snapshot images
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  examples/cephfs/storageclass.yaml
  examples/rbd/snapshotclass.yaml
  examples/rbd/storageclass.yaml
Labels: component/deployment, component/docs

#1102 ci: require ci/centos/containerized-tests for merging
  .mergify.yml
  .travis.yml
Labels: component/testing

#1099 build: verify that all dynamically linked libraries are available
  deploy/cephcsi/image/Dockerfile
Labels: component/deployment

#1084 journal: In mount failure case, suggest to check the kernel logs
  internal/cephfs/nodeserver.go
  internal/rbd/nodeserver.go
Labels: component/cephfs, component/rbd, logging

#1089 CI: Add commitlint bot to travis CI
  .travis.yml
Labels: component/testing

#1107 ci: automatically merge PRs in ci/centos
  .mergify.yml
Labels: Repo activity, component/testing

#1112 ci: do not automatically run jjb-validate on PRs
  jobs/jjb-validate.yaml
Labels: component/testing, ready-to-merge

#1118 ci: Use bionic dist for test environments
  .travis.yml
  scripts/minikube.sh
Labels: component/testing, rebase

#1122 build: use CURDIR instead of PWD
  Makefile
Labels: component/build, ready-to-merge
