Repository ceph/ceph-csi, pull requests merged in 2020-03, with the labels that each got.

#835 Added forcecephkernelclient as startup parameter
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/values.yaml
Labels: backport-to-release-v2.0

#848 Fix mount option issue in rbd
  e2e/rbd.go
  e2e/utils.go
  pkg/rbd/nodeserver.go
Labels: backport-to-release-v2.0, pending-backport-to-downstream

#874 Skip arm64 building in CI
  .travis.yml
Labels: Priority-0, backport-to-release-v2.0

#870 Update upgrade doc for node hang issue
  docs/ceph-csi-upgrade.md
Labels: backport-to-release-v2.0

#867 Update readme for new releases
  README.md
Labels: Release-2.1.0

#871 Bring attacher controller to latest version
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
Labels: Release-2.1.0

#891 examples: rbd/storageclass.yaml causes Python excetion with yamllint
  examples/rbd/storageclass.yaml
Labels: Release-2.1.0

#889 Fix mountpoint issue in rbd helm template
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
Labels: Release-2.1.0

#885 Audit log and follow klog standard
  cmd/cephcsi.go
  pkg/cephfs/controllerserver.go
  pkg/cephfs/nodeserver.go
  pkg/cephfs/volumemounter.go
  pkg/csi-common/driver.go
  pkg/csi-common/server.go
  pkg/liveness/liveness.go
  pkg/rbd/controllerserver.go
  pkg/rbd/nodeserver.go
  pkg/rbd/rbd_attach.go
  pkg/rbd/rbd_util.go
  pkg/util/cachepersister.go
  pkg/util/nodecache.go
Labels: Release-2.1.0

#895 Correct static errors and source code comments.
  pkg/cephfs/controllerserver.go
  pkg/liveness/liveness.go
  pkg/util/conn_pool.go
  pkg/util/vault.go
Labels: Release-2.1.0

#897 Use Error/Log when formatting is not required
  pkg/util/conn_pool_test.go
  pkg/util/pidlimit_test.go
Labels: Release-2.1.0
