Repository ceph/ceph-csi, pull requests merged in 2021-08, with the labels that each got.

#2338 util: getCgroupPidsFile produces striped path when extra : present
  internal/util/pidlimit.go
Labels: backport-to-release-v3.4, bug, component/util

#2349 e2e: use official CentOS container location
  e2e/utils.go
  examples/rbd/block-pod-clone.yaml
  examples/rbd/raw-block-pod.yaml
Labels: backport-to-release-v3.4, component/testing, ready-to-merge

#2292 doc: add design doc for clusterid poolid mapping
  docs/design/proposals/clusterid-mapping.md
Labels: ci/skip/e2e, component/docs

#2308 e2e: retry getting the Services for Ceph MON on failures
  e2e/utils.go
Labels: component/testing, ready-to-merge

#2348 ci: disable commitlint mergify rule
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, component/testing

#2354 e2e: use original namespace for retrying resize check
  e2e/resize.go
Labels: component/testing, ready-to-merge

#2353 cephfs: support selinux mount options
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-psp.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-psp.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/cephfs/kubernetes/csi-nodeplugin-psp.yaml
  deploy/rbd/kubernetes/csi-nodeplugin-psp.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  internal/cephfs/volumeoptions.go
Labels: bug, component/cephfs

#2339 util: add vaultAuthNamespace option for Vault KMS
  examples/kms/vault/kms-config.yaml
  internal/util/vault.go
  internal/util/vault_tokens.go
  internal/util/vault_tokens_test.go
Labels: backport-to-release-v3.4, component/rbd, component/util, enhancement

#2322 util: allow configuring VAULT_AUTH_MOUNT_PATH for Vault Tenant SA KMS
  internal/util/vault.go
  internal/util/vault_sa.go
  internal/util/vault_sa_test.go
Labels: backport-to-release-v3.4, component/rbd, component/util

#2366 doc: update comments in voljournal
  internal/journal/voljournal.go
Labels: ci/skip/e2e, component/docs, ready-to-merge

#2368 rbd: log LastUpdate in UTC format
  internal/rbd/replicationcontrollerserver.go
Labels: component/rbd, backport-to-release-v3.4

#2375 rbd: consider empty mirroring mode
  internal/rbd/replicationcontrollerserver.go
  internal/rbd/replicationcontrollerserver_test.go
Labels: component/rbd, backport-to-release-v3.4

#2381 cleanup: use different file name for testing
  internal/util/cluster_mapping_test.go
Labels: cleanup, component/testing, ci/skip/e2e

#2384 ci: fix ci/centos validation jobs
  deploy/jjb-deploy.yaml
  deploy/jjb-validate.yaml
Labels: bug, component/testing, ready-to-merge

#2376 Allocate slice with size
  internal/csi-common/driver.go
Labels: ready-to-merge

#2395 ci: add `--ignore-not-found=true` to delete namespace in helm cleanup
  mini-e2e-helm.groovy
Labels: component/deployment, component/testing

#2378 ci: remove create & delete namespace commands from helm jobs
  mini-e2e-helm.groovy
Labels: component/deployment, component/testing, ready-to-merge

#2398 rebase: update go-ceph version to v0.11.0
  go.mod
  go.sum
  vendor/github.com/ceph/go-ceph/cephfs/admin/mgrmodule.go
  vendor/github.com/ceph/go-ceph/cephfs/admin/mirror.go
  vendor/github.com/ceph/go-ceph/internal/commands/response.go
  vendor/github.com/ceph/go-ceph/rados/conn.go
  vendor/github.com/ceph/go-ceph/rados/ioctx.go
  vendor/github.com/ceph/go-ceph/rados/object_iter.go
  vendor/github.com/ceph/go-ceph/rados/rados.go
  vendor/github.com/ceph/go-ceph/rbd/encryption.go
  vendor/github.com/ceph/go-ceph/rbd/features.go
  vendor/github.com/ceph/go-ceph/rbd/features_mimic.go
  vendor/github.com/ceph/go-ceph/rbd/mirror.go
  vendor/github.com/ceph/go-ceph/rbd/options.go
  vendor/github.com/ceph/go-ceph/rbd/options_mimic.go
  vendor/github.com/ceph/go-ceph/rbd/options_octopus.go
  vendor/github.com/ceph/go-ceph/rbd/rbd_mimic.go
  vendor/github.com/ceph/go-ceph/rbd/snapshot_mimic.go
  vendor/github.com/ceph/go-ceph/rbd/watchers.go
  vendor/modules.txt
Labels: rebase

#2402 ci: require job for k8s v1.22 in place of v1.19
  .mergify.yml
Labels: component/testing

#2411 ci: use csi sidecar image versions from build.env if available
  single-node-k8s.sh
Labels: component/testing

#2407 ci: dump the rbd-nbd logs
  system-status.sh
Labels: component/testing

#2417 correct interface name and remove redundancy in the interface name
  internal/controller/controller.go
  internal/controller/persistentvolume/persistentvolume.go
Labels: cleanup, component/util

#2421 cleanup: address pylint "consider-using-with" in tracevol.py
  troubleshooting/tools/tracevol.py
Labels: cleanup, ci/skip/e2e

#2423 ci: use pre-pulled image for building e2e.test
  mini-e2e-helm.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#2424 doc: add tickgit TODO badge
  README.md
Labels: component/docs, ready-to-merge, ci/skip/e2e

#2425 doc: add Github release badge to README.md
  README.md
Labels: component/docs, ready-to-merge, ci/skip/e2e

#2393 e2e: improve the debug logs for rbd-nbd
  e2e/rbd.go
Labels: bug, component/testing

#2434 util: fix unit-test for GetClusterMappingInfo()
  internal/util/cluster_mapping.go
  internal/util/cluster_mapping_test.go
Labels: bug, component/testing

#2453 ci: remove the rules for backport on unsupported versions
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e

#2460 ci: skip commitlint for dependabot PRs
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e

#2461 ci: ignore k8s.io/kubernetes dependencies
  .github/dependabot.yml
  go.mod
Labels: Repo activity, component/testing, ci/skip/e2e
