Repository ceph/ceph-csi, pull requests merged in 2021-03, with the labels that each got.

#1891 ci: the "master" branch got renamed to "devel"
  commitlint.groovy
  containerized-tests.groovy
  deploy/ceph-csi-buildconfig.yaml
  jobs/build-images.yaml
  k8s-e2e-external-storage.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  prepare.sh
  scripts/container-needs-rebuild.sh
  scripts/skip-doc-change.sh
  upgrade-tests.groovy
Labels: Repo activity, component/testing, ready-to-merge

#1893 Use Mergify's defaults section for configuring common options
  .mergify.yml
Labels: Repo activity, cleanup, component/build

#1895 Add `kubectl` to the start of command
  charts/ceph-csi-cephfs/README.md
Labels: component/docs, ready-to-merge

#1899 e2e: pass namespace once in deletePodWithLabel()
  e2e/pod.go
Labels: cleanup, component/testing, ready-to-merge

#1888 e2e: make use of ceph users created in e2e
  e2e/ceph_user.go
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/snapshot.go
  e2e/staticpvc.go
  e2e/upgrade-cephfs.go
  e2e/upgrade-rbd.go
  e2e/utils.go
Labels: component/testing

#1898 rebase: use minikube v1.18
  build.env
Labels: component/testing, rebase

#1903 ci: pre-pull ROOK_CEPH_CLUSTER_IMAGE if set
  mini-e2e-helm.groovy
  mini-e2e.groovy
  single-node-k8s.sh
Labels: component/testing, ready-to-merge

#1910 build: libcephfs-devel is not needed
  deploy/cephcsi/image/Dockerfile
  docs/development-guide.md
  scripts/check-env.sh
Labels: cleanup, component/build, dependency/go-ceph, ready-to-merge

#1914 rbd: add more logging for NodeUnstageVolume
  internal/rbd/nodeserver.go
Labels: component/rbd, logging, ready-to-merge

#1557 e2e: update snapshot restore e2e to check data consistency
  e2e/cephfs.go
  e2e/rbd.go
  e2e/upgrade-cephfs.go
  e2e/upgrade-rbd.go
  e2e/utils.go
Labels: component/testing

#1862 Cephfs: Failed to delete snapshot
  e2e/cephfs.go
  e2e/cephfs_helper.go
  internal/cephfs/controllerserver.go
Labels: component/cephfs

#1923 build: regenerate scripts/golangci.yml if build.env was updated
  Makefile
Labels: ci/skip/e2e, component/build, component/testing, ready-to-merge

#1325 rbd: add exclusive-lock and journaling image features for rbd image
  docs/deploy-rbd.md
  e2e/rbd.go
  examples/rbd/storageclass.yaml
  internal/rbd/rbd_util.go
  internal/rbd/rbd_util_test.go
Labels: component/rbd

#1934 util: remove unwanted import string from module dependencies
  cmd/cephcsi.go
  e2e/e2e_test.go
  internal/csi-common/driver.go
  internal/csi-common/nodeserver-default.go
  internal/csi-common/server.go
  internal/csi-common/utils.go
  internal/util/log.go
Labels: cleanup, ready-to-merge

#1932 e2e: verify (non)existence of keys for VaultTokensKMS
  e2e/rbd_helper.go
  e2e/utils.go
Labels: bug, component/testing

#1941 doc: correct reference links in the snapshot,release,upgrade docs
  docs/ceph-csi-upgrade.md
  docs/releases.md
  docs/snap-clone.md
Labels: ci/skip/e2e, component/docs, ready-to-merge

#1945 Add csidriver object for cephfs and rbd
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  charts/ceph-csi-rbd/templates/csidriver-crd.yaml
  deploy/cephfs/kubernetes/csidriver.yaml
  deploy/rbd/kubernetes/csidriver.yaml
  e2e/cephfs.go
  e2e/rbd.go
Labels: component/cephfs, component/deployment, component/rbd
