Repository ceph/ceph-csi, pull requests merged in 2021-09, with the labels that each got.

#2454 doc: remove upgrade instructions for earlier releases
  docs/ceph-csi-upgrade.md
Labels: cleanup, component/docs, ci/skip/e2e

#2436 cleanup: move cephfs errors to new util packages
  internal/cephfs/cephfs_util.go
  internal/cephfs/clone.go
  internal/cephfs/clone_test.go
  internal/cephfs/controllerserver.go
  internal/cephfs/errors/errors.go
  internal/cephfs/fsjournal.go
  internal/cephfs/nodeserver.go
  internal/cephfs/snapshot.go
  internal/cephfs/volume.go
  internal/cephfs/volumeoptions.go
Labels: cleanup, component/cephfs

#2408 cephfs: remove explicit size setting of cloned volume
  internal/cephfs/controllerserver.go
Labels: component/cephfs, dependency/ceph

#2480 ci: prevent mergify conflict message for dependabot PRs
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e

#2479 cleanup: add checkErrAndUndoReserve() for error check and unreserve omap in deleteVolume
  internal/rbd/controllerserver.go
Labels: cleanup, component/rbd

#2484 rbd: use String() method of MirrorImageState in return error
  internal/rbd/replicationcontrollerserver.go
Labels: component/rbd

#2482 cleanup: introduce populateRbdVol(), to fill rbdVol from stage req
  internal/rbd/nodeserver.go
Labels: cleanup, component/rbd

#2477 rbd: avoid supplying map options on unmap
  internal/rbd/rbd_attach.go
  internal/rbd/rbd_util.go
Labels: component/rbd

#2486 cleanup: simplify checkStaticVolume function and remove unwanted vars
  internal/controller/persistentvolume/persistentvolume.go
Labels: cleanup

#2493 util: read ceph.conf by calling conn.ReadConfigFile(CephConfigPath)
  internal/util/conn_pool.go
Labels: component/util, backport-to-release-v3.4

#2496 rbd: set vaultAuthNamespace to vaultNamespace if empty
  internal/kms/vault.go
Labels: bug, component/rbd, backport-to-release-v3.4

#2497 util: call WriteCephConfig() in cephcsi.go
  cmd/cephcsi.go
  internal/cephfs/driver.go
  internal/rbd/driver.go
Labels: component/util, backport-to-release-v3.4

#2498 ci: pass $DISK_CONFIG properly to minikube start
  scripts/minikube.sh
Labels: component/testing, ready-to-merge, backport-to-release-v3.3, backport-to-release-v3.4

#2490 ci: use internal minikube extra disks functionality
  single-node-k8s.sh
Labels: component/testing, ready-to-merge

#2495 cleanup: correct checkReservation return description
  internal/journal/voljournal.go
Labels: cleanup

#2499 ci : remove support for backward compatibility for psp
  scripts/minikube.sh
Labels: component/testing

#2508 ci: set NUM_DISKS default value to 1 in minikube.sh
  scripts/minikube.sh
Labels: component/testing

#2507 rbd: Report errors when a resync maybe in progress
  internal/rbd/replicationcontrollerserver.go
Labels: component/rbd

#2517 build: set build environment variables
  .github/workflows/publish-artifacts.yaml
Labels: component/build, ci/skip/e2e

#2532 ci: disable fsGroupChangePolicy change test for cephfs
  scripts/k8s-storage/driver-cephfs.yaml
Labels: component/testing

#2522 cleanup: rework on naming conventions
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  charts/ceph-csi-cephfs/README.md
  cmd/cephcsi.go
  docs/resource-cleanup.md
  e2e/README.md
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/e2e_test.go
  e2e/rbd_helper.go
  e2e/snapshot.go
  e2e/upgrade-cephfs.go
  e2e/utils.go
  examples/csi-config-map-sample.yaml
Labels: cleanup

#2540 rebase: update minikube to v1.23.2
  build.env
Labels: rebase, component/testing

#2543 rebase: update vault/api to v1.1.1
  go.mod
  go.sum
  vendor/github.com/cenkalti/backoff/v3/.gitignore
  vendor/github.com/cenkalti/backoff/v3/.travis.yml
  vendor/github.com/cenkalti/backoff/v3/LICENSE
  vendor/github.com/cenkalti/backoff/v3/README.md
  vendor/github.com/cenkalti/backoff/v3/backoff.go
  vendor/github.com/cenkalti/backoff/v3/context.go
  vendor/github.com/cenkalti/backoff/v3/exponential.go
  vendor/github.com/cenkalti/backoff/v3/go.mod
  vendor/github.com/cenkalti/backoff/v3/retry.go
  vendor/github.com/cenkalti/backoff/v3/ticker.go
  vendor/github.com/cenkalti/backoff/v3/tries.go
  vendor/github.com/hashicorp/go-hclog/interceptlogger.go
  vendor/github.com/hashicorp/go-hclog/intlogger.go
  vendor/github.com/hashicorp/go-hclog/logger.go
  vendor/github.com/hashicorp/vault/api/README.md
  vendor/github.com/hashicorp/vault/api/client.go
  vendor/github.com/hashicorp/vault/api/go.mod
  vendor/github.com/hashicorp/vault/api/go.sum
  vendor/github.com/hashicorp/vault/api/lifetime_watcher.go
  vendor/github.com/hashicorp/vault/api/output_string.go
  vendor/github.com/hashicorp/vault/api/plugin_helpers.go
  vendor/github.com/hashicorp/vault/api/sys_audit.go
  vendor/github.com/hashicorp/vault/api/sys_auth.go
  vendor/github.com/hashicorp/vault/api/sys_config_cors.go
  vendor/github.com/hashicorp/vault/api/sys_leader.go
  vendor/github.com/hashicorp/vault/api/sys_leases.go
  vendor/github.com/hashicorp/vault/api/sys_plugins.go
  vendor/github.com/hashicorp/vault/api/sys_raft.go
  vendor/github.com/hashicorp/vault/api/sys_rotate.go
  vendor/modules.txt
Labels: rebase, ready-to-merge

#2544 ci: automatically run k8s-e2e-external-storage/1.22 job
  jobs/k8s-e2e-external-storage.yaml
Labels: component/testing

#2545 ci: require passing of k8s-e2e-external-storage jobs for merge
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e

#2550 doc: update dev standup meeting link
  README.md
Labels: component/docs, ci/skip/e2e
