Repository ceph/ceph-csi, pull requests merged in 2021-04, with the labels that each got.

#1949 cleanup: correct misspelling
  e2e/rbd.go
Labels: ci/skip/e2e, cleanup, component/docs, component/rbd, ready-to-merge

#1952 cleanup: correct misspelling in rbd/clone.go
  internal/rbd/clone.go
Labels: ci/skip/e2e, cleanup, ready-to-merge

#1955 deploy: use serviceAccountName instead of serviceAccount in yamls
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  docs/ceph-csi-upgrade.md
  examples/kms/vault/vault.yaml
Labels: cleanup, component/deployment, ready-to-merge

#1957 [RBD DR] Fix force promoteVolume
  internal/rbd/replicationcontrollerserver.go
Labels: component/rbd

#1950 rbd: encrypted volumes can be of type "crypto_LUKS" too
  internal/rbd/nodeserver.go
Labels: component/rbd

#1958 ci: Update mergify rules for containerized-tests
  .mergify.yml
Labels: ci/skip/e2e, component/testing

#1960 doc: update dev standup timing
  README.md
Labels: ci/skip/e2e, component/docs

#1961 ci: Disable containerized-tests job
  jobs/containerized-tests.yaml
Labels: component/testing

#1962 ci: do not re-checkout current branch
  ci-job-validation.groovy
  containerized-tests.groovy
  k8s-e2e-external-storage.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1964 cephfs: add stderr to mount function errors
  internal/cephfs/volumemounter.go
Labels: component/cephfs, logging

#1970 ci: only abort on doc-change when running for PRs
  ci-job-validation.groovy
  containerized-tests.groovy
  k8s-e2e-external-storage.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#1966 util: add nil check to default ControllerGetCapabilities()
  internal/csi-common/controllerserver-default.go
Labels: component/util, ready-to-merge

#1973 ci: update feature gates setting from minikube.sh
  scripts/minikube.sh
Labels: component/deployment, ready-to-merge

#1976 cleanup: update mergify.yml to use merge_bot_account option
  .mergify.yml
Labels: ci/skip/e2e, component/testing

#1981 revert: cleanup: update mergify.yml to use merge_bot_account option
  .mergify.yml
Labels: ci/skip/e2e, component/testing

#1982 ci: add mergify rules for release 3.3
  .mergify.yml
Labels: ci/skip/e2e, component/testing

#1985 Update Readme for available image tags
  README.md
Labels: component/docs, ready-to-merge

#1984 revert: update templates for v3.3.0 release
  build.env
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: component/deployment, ready-to-merge

#1959 cephfs: enable ceph-fuse big_writes by default
  internal/util/cephconf.go
Labels: component/cephfs

#1989 cleanup: update description to generic
  internal/rbd/rbd_util.go
Labels: ci/skip/e2e, component/docs

#1990 rebase: update minikube to version 1.19.0
  build.env
Labels: component/testing, ready-to-merge, rebase

#1840 Remove losetup workaround in minikube VM
  scripts/minikube.sh
Labels: component/testing, dependency/k8s

#1991 rbd: modified logic to check image watchers
  internal/rbd/rbd_util.go
Labels: backport-to-release-v3.3, component/rbd

#1997 doc: update upgrade doc for v3.3.0
  docs/ceph-csi-upgrade.md
Labels: ci/skip/e2e, component/docs

#2000 cleanup: correct typo in travis scripts
  scripts/travis-functest.sh
  scripts/travis-helmtest.sh
Labels: ci/skip/e2e, cleanup, component/docs, ready-to-merge

#2001 rbd: return crypt error for the rpc return
  internal/rbd/controllerserver.go
Labels: backport-to-release-v3.3, component/rbd

#2007 build: Fix helm chart pushing
  deploy.sh
Labels: backport-to-release-v3.3, ci/skip/e2e, component/build

#2009 deploy: update templates for v3.3.1
  build.env
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: component/deployment

#2012 cleanup: fix author in mergifyio backport conditions
  .mergify.yml
Labels: ci/skip/e2e, component/testing

#2011 revert: update templates for v3.3.1
  build.env
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: component/deployment

#2019 Replace deprecated GitVersion with Version
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  charts/ceph-csi-cephfs/templates/provisioner-clusterrole.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/templates/csidriver-crd.yaml
Labels: component/deployment, ready-to-merge

#2014 ci: enable running of k8s-e2e-external-storage job by default
  jobs/k8s-e2e-external-storage.yaml
Labels: component/testing, ready-to-merge

#2016 testing: enable nodeExpansion for k8s-storage rbd-rwo verification
  scripts/k8s-storage/driver-rbd-rwo.yaml
Labels: component/rbd, component/testing

#2024 ci: pre-pull the required container images
  k8s-e2e-external-storage.groovy
Labels: component/testing, ready-to-merge

#2026 ci: add missing ci_registry k8s-e2e-external-storage groovy
  k8s-e2e-external-storage.groovy
Labels: component/testing, ready-to-merge

#1953 build: use latest pacific release of ceph
  build.env
Labels: dependency/ceph, ready-to-merge, rebase

#2030 ci: pre-pull busybox container image
  k8s-e2e-external-storage.groovy
Labels: component/testing

#2036 ci: fix k8s-e2e-external-storage fails
  k8s-e2e-external-storage.groovy
Labels: bug, component/testing

#2035 helm: update external-snapshotter image to v4.0.0
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
Labels: component/deployment, ready-to-merge, rebase

#2021 rbd: delete encryption key from KMS
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/snapshot.go
  e2e/utils.go
  internal/rbd/snapshot.go
Labels: backport-to-release-v3.3, component/rbd
