Repository ceph/ceph-csi, pull requests merged in 2021-06, with the labels that each got.

#2112 rbd: fix typo in error message
  internal/rbd/rbd_util.go
Labels: component/rbd, logging, ready-to-merge

#2101 Continue thick-provisioning of RBD images on CreateVolume restart
  internal/rbd/controllerserver.go
  internal/rbd/controllerserver_test.go
  internal/rbd/rbd_util.go
Labels: backport-to-release-v3.3, bug, component/rbd

#2127 cephfs: pass extra volume attributes to static PV (Issue #2114)
  internal/cephfs/volumeoptions.go
Labels: component/cephfs

#2129 cleanup: address wasted assign issues
  e2e/utils.go
  internal/rbd/controllerserver.go
  internal/util/vault.go
Labels: cleanup, ready-to-merge

#2140 ci: pass GITHUB_BASE_REF when running commitlint
  .github/workflows/commitlint.yaml
  Makefile
Labels: ci/skip/e2e, component/testing

#2111 rbd: fail fast in create volume for missmatch encryption
  internal/rbd/controllerserver.go
  internal/rbd/rbd_util.go
Labels: backport-to-release-v3.3, component/rbd

#2150 build: use cephcsi bot token to push helm charts
  .github/workflows/publish-artifacts.yaml
Labels: ci/skip/e2e, component/build, component/deployment

#2160 util: returns actual error instead of ErrPoolNotFound
  internal/util/cephcmds.go
Labels: component/util, logging, ready-to-merge

#2154 doc: correct comment indentation in rbdVolume
  internal/rbd/rbd_util.go
Labels: ci/skip/e2e, cleanup, component/docs

#2155 cleanup: gocyclo being unused for linter
  internal/rbd/controllerserver.go
  internal/rbd/nodeserver.go
  internal/rbd/replicationcontrollerserver.go
  internal/util/csiconfig_test.go
Labels: ci/skip/e2e, cleanup

#2158 doc: adds note to replace canary with version tag
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
Labels: ci/skip/e2e, component/docs

#2159 rebase: update minikube to v1.21.0
  build.env
Labels: ready-to-merge, rebase

#2162 rbd: check stdErr for does not have a parent error
  internal/rbd/rbd_util.go
Labels: component/rbd, ready-to-merge

#2161 e2e: validate images in trash
  e2e/rbd.go
  e2e/rbd_helper.go
Labels: component/rbd, component/testing, ready-to-merge

#2165 doc: add imageFeatures parameter info to static-pvc.md
  docs/static-pvc.md
Labels: ci/skip/e2e, component/docs

#2170 testing: pass --delete-on-failure when starting minikube
  scripts/minikube.sh
Labels: component/testing, ready-to-merge

#2173 ci: disable push artifacts on forked repo
  .github/workflows/publish-artifacts.yaml
Labels: ci/skip/e2e, component/testing

#2175 rbd: correct return error for isCompatibleEncryption
  internal/rbd/rbd_util.go
Labels: component/rbd, logging, ready-to-merge

#2126 cleanup: Modifies Wrapcheck linter
  e2e/cephfs_helper.go
  e2e/configmap.go
  e2e/namespace.go
  e2e/node.go
  e2e/pod.go
  e2e/pvc.go
  e2e/rbd_helper.go
  e2e/resize.go
  e2e/snapshot.go
  e2e/staticpvc.go
  e2e/utils.go
  internal/controller/controller.go
  internal/controller/persistentvolume/persistentvolume.go
  internal/journal/voljournal.go
Labels: cleanup

#2195 e2e: remove bootstrapper BeforeEach and AfterEach
  e2e/e2e_test.go
Labels: cleanup, component/testing, ready-to-merge

#2194 helm: add support to pass --namespace option
  scripts/install-helm.sh
Labels: component/deployment, component/testing

#2183 cleanup: correct initResources() function name typo
  e2e/e2e_test.go
  e2e/utils.go
Labels: cleanup, component/testing

#2184 rbd: use DeepCopy() to create thick-provisioned volumes from a snapshot
  internal/rbd/controllerserver.go
Labels: backport-to-release-v3.3, bug, component/rbd

#2013 ci: update mini-e2e-helm job as per script changes
  mini-e2e-helm.groovy
Labels: component/deployment, component/testing

#2206 e2e: provide an option if tests run on helm deployment
  e2e/e2e_test.go
  e2e/utils.go
Labels: backport-to-release-v3.3, ci/skip/e2e, component/deployment, component/testing, ready-to-merge

#2193 cleanup: prevent panic in cleanUpSnapshot
  internal/rbd/snapshot.go
Labels: Priority-0, backport-to-release-v3.3, bug, cleanup, component/rbd, ready-to-merge

#2164 cleanup: addresses paralleltest linter
  e2e/e2e_test.go
  internal/csi-common/utils_test.go
  internal/rbd/nodeserver_test.go
  internal/rbd/rbd_util_test.go
  internal/util/aws_metadata_test.go
  internal/util/conn_pool_test.go
  internal/util/crypto_test.go
  internal/util/csiconfig_test.go
  internal/util/errors_test.go
  internal/util/idlocker_test.go
  internal/util/kms_test.go
  internal/util/pidlimit_test.go
  internal/util/secretskms_test.go
  internal/util/topology_test.go
  internal/util/util_test.go
  internal/util/vault_test.go
  internal/util/vault_tokens_test.go
  internal/util/volid_test.go
Labels: cleanup, component/testing

#2213 cleanup: error is not nil but returns nil
  e2e/pvc.go
  e2e/rbd_helper.go
  e2e/utils.go
Labels: cleanup, component/testing, priority-3

#2203 e2e: disable iss validation in Hashicorp Vault
  examples/kms/vault/vault.yaml
Labels: Priority-2, backport-to-release-v3.3, component/testing, ready-to-merge

#2212 cleanup: use %w to format errors
  e2e/pvc.go
  e2e/snapshot.go
Labels: cleanup, logging, priority-3, ready-to-merge

#2095 e2e: validate encryption keys in KMS
  e2e/rbd.go
  e2e/utils.go
Labels: Priority-2, component/testing, ready-to-merge

#2218 e2e: check isRetryableAPIError during polling
  e2e/errors.go
  e2e/pod.go
  e2e/pvc.go
  e2e/snapshot.go
Labels: component/testing, priority-4, ready-to-merge

#2233 ci: skip Ephemeral-volume kubernetes external-storage tests
  run-k8s-external-storage-e2e.sh
Labels: component/testing, ready-to-merge

#2230 ci: require CI jobs with Kubernetes 1.21 to pass
  .mergify.yml
Labels: Repo activity, component/testing

#2223 e2e: force deploying SC and Secret
  jobs/mini-e2e-helm-sc.yaml
  mini-e2e-helm-sc.groovy
Labels: component/testing, ready-to-merge

#2232 e2e: do not create a single-item list
  examples/kms/vault/vault.yaml
Labels: cleanup, component/testing, ready-to-merge
