Repository ceph/ceph-csi, pull requests merged in 2021-07, with the labels that each got.

#2245 ci: fix helm job failure
  mini-e2e-helm.groovy
Labels: bug, component/deployment, component/testing, ready-to-merge

#2251 cleanup: resolves gocritic linter issues
  e2e/rbd.go
  internal/rbd/nodeserver.go
  internal/rbd/replicationcontrollerserver.go
Labels: cleanup

#2236 doc: update helm chart documentations
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-rbd/README.md
Labels: ci/skip/e2e, component/deployment, component/docs

#2249 util: more generic kernel version parsing
  internal/util/util.go
  internal/util/util_test.go
Labels: component/util

#2243 cleanup: resolve exhaustive linter
  e2e/pod.go
  internal/cephfs/clone.go
  internal/cephfs/errors.go
Labels: cleanup

#2266 cleanup: Adds t.Helper() to test helper function
  internal/util/topology_test.go
Labels: ci/skip/e2e, cleanup

#2257 doc: Updates the helm doc with secret and storageclass configurations
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-rbd/README.md
Labels: ci/skip/e2e, component/deployment, component/docs

#2270 cleanup: refactor e2e KMS configuration and usage
  e2e/kms.go
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/utils.go
Labels: cleanup, component/testing

#2256 cleanup: resolve godot linter
  cmd/cephcsi.go
  e2e/ceph_user.go
  e2e/rbd.go
  e2e/utils.go
  internal/cephfs/driver.go
  internal/cephfs/errors.go
  internal/cephfs/volumemounter.go
  internal/rbd/driver.go
  internal/rbd/encryption.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_attach.go
  internal/util/aws_metadata.go
  internal/util/cephconf.go
  internal/util/connection.go
  internal/util/crypto.go
  internal/util/csiconfig.go
  internal/util/idlocker.go
  internal/util/kms.go
  internal/util/secretskms.go
  internal/util/util.go
  internal/util/vault.go
Labels: ci/skip/e2e, cleanup, ready-to-merge

#2269 doc: add documentaion for rbd-nbd mounter
  README.md
  docs/rbd-nbd.md
Labels: ci/skip/e2e, component/docs, ready-to-merge

#2267 cleanup: resolve parallel test issue
  internal/rbd/controllerserver_test.go
  internal/rbd/replicationcontrollerserver_test.go
  internal/util/conn_pool_test.go
Labels: ci/skip/e2e, cleanup

#2227 doc: proposal for KMS with ServiceAccount per Tenant
  docs/design/proposals/encryption-with-vault-sa.md
Labels: ci/skip/e2e, component/docs

#2247 cleanup: spell check getImageMirroingStatus
  internal/rbd/mirror.go
  internal/rbd/replicationcontrollerserver.go
Labels: cleanup, ready-to-merge

#2274 cleanup: ineffective assignment
  internal/cephfs/controllerserver.go
Labels: cleanup

#2278 cleanup: resolves gofumpt for cmd
  cmd/cephcsi.go
Labels: cleanup

#2276 cleanup: resolves gofumpt issues of internal codes
  internal/cephfs/nodeserver.go
  internal/cephfs/volume.go
  internal/cephfs/volumeoptions.go
  internal/controller/persistentvolume/persistentvolume.go
  internal/csi-common/utils.go
  internal/journal/voljournal.go
  internal/liveness/liveness.go
  internal/rbd/controllerserver.go
  internal/rbd/driver.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_journal.go
  internal/rbd/rbd_util.go
  internal/rbd/replicationcontrollerserver.go
  internal/util/cephconf.go
  internal/util/conn_pool_test.go
  internal/util/crypto.go
  internal/util/csiconfig_test.go
  internal/util/httpserver.go
  internal/util/idlocker_test.go
  internal/util/pidlimit_test.go
  internal/util/topology.go
  internal/util/topology_test.go
  internal/util/util.go
  internal/util/util_test.go
  internal/util/volid.go
Labels: cleanup

#2287 ci: do not use Groovy string interpolation for credentials
  ci-job-validation.groovy
  containerized-tests.groovy
  k8s-e2e-external-storage.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#2291 ci: quote username for podman_login()
  ci-job-validation.groovy
  containerized-tests.groovy
  k8s-e2e-external-storage.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#2253 rebase: update minikube to v1.22.0
  build.env
Labels: component/testing, ready-to-merge, rebase

#2294 ci: add the root user to the libvirt group
  prepare.sh
Labels: component/testing, ready-to-merge

#2261 util: remove deleteLock check while acquiring snapshot createLock
  internal/util/idlocker.go
Labels: component/util, ready-to-merge

#2273 cleanup: resolve revive linter issue
  e2e/kms.go
  e2e/rbd_helper.go
  internal/journal/voljournal.go
Labels: cleanup, ready-to-merge

#2265 cleanup: resolve errorlint issues
  e2e/rbd_helper.go
  e2e/snapshot.go
  e2e/utils.go
  internal/rbd/rbd_attach.go
  internal/rbd/rbd_util.go
  internal/util/pidlimit.go
  internal/util/topology.go
  internal/util/topology_test.go
Labels: cleanup

#2290 doc: describe Hashicorp Vault with a ServiceAccount per Tenant
  docs/deploy-rbd.md
Labels: ci/skip/e2e, component/docs, ready-to-merge

#2277 cleanup: resolves gofumpt issues in e2e
  e2e/cephfs.go
  e2e/configmap.go
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/upgrade-cephfs.go
  e2e/upgrade-rbd.go
  e2e/utils.go
Labels: cleanup, component/testing, ready-to-merge

#2306 doc: explicitly mention volume/pv metrics feature
  README.md
Labels: ci/skip/e2e, component/docs, priority-1, ready-to-merge

#2304 doc: lift snapshot creation/deletion and new volume creation support to Beta
  README.md
Labels: ci/skip/e2e, component/docs, priority-1, ready-to-merge

#2302 e2e: retry on "connect: connection refused" errors
  e2e/errors.go
Labels: component/testing, ready-to-merge

#2310 cleanup: fix beta apiVersion for csidriver
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  deploy/cephfs/kubernetes/csidriver.yaml
  deploy/rbd/kubernetes/csidriver.yaml
  examples/cephfs/snapshot.yaml
  examples/cephfs/snapshotclass.yaml
  examples/rbd/snapshot.yaml
  examples/rbd/snapshotclass.yaml
Labels: bug, cleanup, ready-to-merge

#2307 util: allow configuring VAULT_BACKEND for Vault connection
  examples/kms/vault/kms-config.yaml
  examples/kms/vault/tenant-config.yaml
  examples/kms/vault/tenant-sa-admin.yaml
  examples/kms/vault/tenant-sa.yaml
  internal/util/vault.go
  internal/util/vault_tokens.go
  internal/util/vault_tokens_test.go
Labels: component/rbd, component/util, enhancement

#2312 e2e: isRetryableAPIError() should match any etcdserver timeout
  e2e/errors.go
Labels: component/testing

#2317 ci: fix yamllint error in generated golangci.yml file
  scripts/golangci.yml.in
Labels: bug, component/testing, ready-to-merge

#2201 rbd: use go-ceph for getImageMirroringStatus
  internal/rbd/mirror.go
  internal/rbd/replicationcontrollerserver.go
Labels: Priority-2, component/rbd

#2320 doc: Add documentation for Disaster Recovery
  docs/disaster-recovery.md
Labels: ci/skip/e2e, component/docs

#2330 ci: add Mergify backport rules for release-v3.4
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, component/testing

#2331 doc: update the upgrade documentation to reflect 3.4.0 changes
  docs/ceph-csi-upgrade.md
Labels: ci/skip/e2e, component/docs

#2325 e2e: retry deploying CephFS components on failure
  e2e/cephfs.go
Labels: component/testing, ready-to-merge

#2334 deploy: revert changes made for 3.4.0 release
  build.env
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: ready-to-merge

#2333 build: install specific commitlint version
  build.env
  scripts/Dockerfile.test
Labels: ci/skip/e2e, component/build

#2298 e2e: sync data from rbd-nbd mount
  e2e/rbd.go
Labels: bug, component/testing

#2340 deploy: add non-default namespace support for rbd kubernetes manifest files
  deploy/rbd/kubernetes/csi-nodeplugin-rbac.yaml
  deploy/rbd/kubernetes/csi-provisioner-rbac.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: backport-to-release-v3.4, component/deployment, ready-to-merge
