Repository ceph/ceph-csi, pull requests merged in 2021-11, with the labels that each got.

#2608 ci: do not let dependabot automatically rebase
  .github/dependabot.yml
Labels: component/testing, ci/skip/e2e

#2529 rbd: utilize cookie support from rbd for nbd
  internal/rbd/rbd_attach.go
Labels: component/rbd

#2609 doc: add migration design documentation
  docs/design/proposals/intree-migrate.md
Labels: priority-1, component/docs, dependency/k8s, ci/skip/e2e

#2627 cleanup: fix log level
  internal/util/util.go
Labels: bug, cleanup

#2628 e2e: restrict IO with lower version kernel at rbd-nbd tests
  e2e/rbd.go
Labels: component/testing

#2642 ci: remove gh action gosec linter,since it is already part of golangci
  .github/workflows/gosec.yaml
  .mergify.yml
  Makefile
  build.env
  scripts/Dockerfile.test
  scripts/gosec.sh
Labels: component/testing, ci/skip/e2e

#2645 rebase: replace vendored layeh.com/radius with GitHub source
  go.mod
  go.sum
  vendor/modules.txt
Labels: rebase, ready-to-merge, ci/skip/e2e

#2615 e2e: retry when a "transport is closing" error is hit
  e2e/errors.go
Labels: component/testing

#2646 build: use golang:1.16 as runtime container for retest action
  actions/retest/Dockerfile
Labels: component/build, ci/skip/e2e

#2618 rbd: call undoStagingTransaction() when NodeStageVolume() fails
  internal/rbd/nodeserver.go
Labels: component/rbd, ci/retry/e2e

#2621 rbd: log stdError for cryptosetup commands
  internal/util/crypto.go
  internal/util/cryptsetup.go
Labels: component/rbd, ci/retry/e2e

#2649 ci: add actions/retest to dependabot checks
  .github/dependabot.yml
Labels: component/testing, ready-to-merge, ci/skip/e2e

#2623 cleanup: log the image name and pool name
  internal/rbd/nodeserver.go
Labels: cleanup, ci/retry/e2e

#2659 ci: update images for vault 1.8.5
  mini-e2e-helm.groovy
  mini-e2e.groovy
  mirror/images.txt
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#2660 ci: use official CentOS container location
  deploy/Dockerfile
  mirror/Containerfile
Labels: component/testing, ready-to-merge

#2658 ci: use 1.8.5 vault for e2e
  examples/kms/vault/vault.yaml
Labels: component/testing, ci/retry/e2e

#2654 deploy: deploy erasure coded pool
  scripts/rook.sh
Labels: component/testing, ci/skip/e2e, backport-to-release-v3.4

#2622 ci: update minikube to v1.24.0
  build.env
Labels: component/testing, ci/retry/e2e

#2664 ci: fix helm chart push for release branches
  .github/workflows/publish-artifacts.yaml
Labels: bug, component/deployment, component/testing

#2666 ci: use refs/pull/<id>/merge in k8s external storage tests too
  k8s-e2e-external-storage.groovy
Labels: component/testing

#2669 rbd: do deep copy for dummyVol struct
  internal/rbd/replicationcontrollerserver.go
Labels: Priority-0, component/rbd, ci/skip/e2e, ci/retry/e2e

#2674 ci: have mergify label PRs for `actions/` with `ci/skip/e2e`
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e

#2676 Revert "ci: have Mergify label PRs for `actions/` with `ci/skip/e2e`"
  .mergify.yml
Labels: Repo activity

#2651 e2e: retry on "transport: missing content-type field" error
  e2e/errors.go
Labels: component/testing

#2663 helm: use "version: 3-canary" for helm charts on "devel"
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-rbd/Chart.yaml
Labels: component/deployment, ci/skip/e2e

#2670 ci: use only latest version of test status in retest action
  actions/retest/main.go
Labels: component/testing, ci/skip/e2e

#2619 helm: csi-rbd Fix invalid yaml generation on ceph-csi-config
  charts/ceph-csi-rbd/templates/csiplugin-configmap.yaml
Labels: component/deployment

#2652 rbd: repair imageid after resync
  internal/rbd/rbd_journal.go
  internal/rbd/replicationcontrollerserver.go
Labels: bug, Priority-0, component/rbd, ci/retry/e2e

#2653 ci: deploy erasure coded pool
  single-node-k8s.sh
Labels: component/testing
