Repository ceph/ceph-csi, pull requests merged in 2021-05, with the labels that each got.

#2037 ci: provide k8s-e2e-external-storage jobs for different k8s versions
  jobs/k8s-e2e-external-storage.yaml
Labels: component/testing, dependency/k8s, ready-to-merge

#2041 build: template changes for release v3.2.2
  build.env
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: component/build

#2038 e2e: update rook ceph cluster image version
  build.env
Labels: component/testing, dependency/rook, rebase

#2046 revert: template changes for release v3.2.2
  build.env
  charts/ceph-csi-cephfs/Chart.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/Chart.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: component/build, component/deployment

#2047 ci: apply standard Mergify rules for release branches too
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, component/testing

#2050 ci: drop quotes for Mergify regex matching
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, component/testing

#2054 ci: use mergify to add labels to PRs
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, component/testing

#2028 rbd: mark image as ready when image states is up+unknown
  internal/rbd/replicationcontrollerserver.go
Labels: backport-to-release-v3.3, component/rbd

#2056 cleanup: address gosec complaint about creating a file
  internal/rbd/nodeserver.go
Labels: ci/skip/e2e, cleanup, component/testing, ready-to-merge

#2058 ci: increase memory for minikube VM to 14GB
  single-node-k8s.sh
Labels: component/testing, ready-to-merge

#2057 ci: update mergify config for labelling PRs
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, ready-to-merge

#2065 doc: update readme for latest releases
  README.md
Labels: ci/skip/e2e, component/docs, ready-to-merge

#2068 ci: run system-status.sh in case a job fails
  k8s-e2e-external-storage.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  system-status.sh
  upgrade-tests.groovy
Labels: component/testing, ready-to-merge

#2073 ci: use "top -w" for untruncated wide output
  system-status.sh
Labels: component/testing, ready-to-merge

#2074 ci: use "-T" to display the filesystem type
  system-status.sh
Labels: component/testing

#2076 ci: include status of the Rook deployment on failure
  system-status.sh
Labels: component/testing, ready-to-merge

#2078 ci: get the logs from the Ceph cluster pods
  system-status.sh
Labels: component/testing, ready-to-merge

#2082 ci: capture more logs from the rook-ceph namespace on failure
  system-status.sh
Labels: component/testing, ready-to-merge

#2083 ci: have mergify set the component/build label on PRs
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, component/testing

#2085 ci: rebuild infra container images after merge
  jobs/jjb-deploy.yaml
Labels: component/testing, ready-to-merge

#2090 ci: log previous instance of the container in a pod
  system-status.sh
Labels: component/testing, ready-to-merge

#2087 ci: fix running ceph -s in toolbox pod
  system-status.sh
Labels: bug, component/testing, ready-to-merge

#2088 ci: get logs from all containers in pod in system-status.sh
  system-status.sh
Labels: component/testing

#2091 ci: get logs from all pods, not only the 1st
  system-status.sh
Labels: component/testing, ready-to-merge

#2092 ci: update upgrade-version to v3.3.1 for upgrade tests
  jobs/upgrade-tests.yaml
Labels: component/testing

#1983 cleanup: update mergify.yml to remove bot_account option
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, cleanup

#2064 build: update go version to 1.16 in go.mod
  build.env
  docs/development-guide.md
  go.mod
  scripts/check-env.sh
  vendor/modules.txt
Labels: component/build, ready-to-merge, rebase

#1935 util: enable golang profiling
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
  cmd/cephcsi.go
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  internal/cephfs/driver.go
  internal/rbd/driver.go
  internal/util/httpserver.go
  internal/util/util.go
Labels: enhancement

#2100 ci: add wait-timeout,wait flag to minikube start
  scripts/minikube.sh
Labels: component/testing

#2067 helm: fix k8s version string for csidriver crds semverCompare
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  charts/ceph-csi-rbd/templates/csidriver-crd.yaml
Labels: bug, component/deployment

#2060 rebase: update minikube to v1.20.0
  build.env
Labels: component/testing, rebase

#2062 cleanup: remove unnecessary calling of .String() when logging
  internal/rbd/controllerserver.go
  internal/rbd/encryption.go
  internal/rbd/mirror.go
  internal/rbd/rbd_attach.go
  internal/rbd/rbd_util.go
Labels: cleanup, logging

#2106 cephfs: return GRPC error in NodeGetVolumeStats
  internal/cephfs/nodeserver.go
Labels: bug, component/cephfs
