Repository ceph/ceph-csi, pull requests merged in 2022-02, with the labels that each got.

#2838 ci: request CentOS Stream 8 bare-metal machines
  ci-job-validation.groovy
  commitlint.groovy
  containerized-tests.groovy
  k8s-e2e-external-storage.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing

#2853 ci: pass GOARCH when building images in OpenShift
  jobs/build-images.yaml
Labels: component/testing

#2851 e2e: use `pstree` instead of `ps` for checking rbd-nbd process
  e2e/rbd.go
Labels: component/testing, backport-to-release-v3.5

#2789 deploy: update csi-snapshotter sidecar to v5.0.1
  build.env
  charts/ceph-csi-cephfs/templates/provisioner-clusterrole.yaml
  charts/ceph-csi-rbd/templates/provisioner-clusterrole.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-provisioner-rbac.yaml
  deploy/rbd/kubernetes/csi-provisioner-rbac.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  docs/snap-clone.md
  scripts/install-snapshot.sh
  scripts/snapshot-controller-psp.yaml
Labels: rebase, ci/retry/e2e

#2857 ci: use CentOS Stream 8 for infra containers
  deploy/Dockerfile
  mirror/Containerfile
Labels: component/testing

#2827 cleanup: remove ceph.conf WA options which are already fixed
  charts/ceph-csi-rbd/values.yaml
  examples/ceph-conf.yaml
  internal/util/cephconf.go
Labels: bug, cleanup, ci/retry/e2e

#2862 util: use `vaultNamespace` if `vaultAuthNamespace` is not set
  internal/kms/vault.go
  internal/kms/vault_tokens_test.go
Labels: bug, component/util, backport-to-release-v3.5

#2865 rbd: add AAD(additionalauthdata) while unwrapping the DEK
  internal/kms/keyprotect.go
Labels: bug, priority-1, component/rbd, ci/skip/e2e, backport-to-release-v3.5

#2868 rbd: remove kp-metadata register functions of HPCS/Key Protect
  internal/kms/keyprotect.go
Labels: cleanup, component/rbd

#2844 cephfs: fix omap deletion in DeleteSnapshot
  internal/cephfs/controllerserver.go
Labels: bug, component/cephfs, backport-to-release-v3.5

#2830 rbd : Fix dataPool in createVolumeResponse
  internal/rbd/controllerserver.go
Labels: bug, component/rbd, ci/retry/e2e

#2871 helm: remove namespace from storageclass yaml
  charts/ceph-csi-cephfs/templates/storageclass.yaml
  charts/ceph-csi-rbd/templates/storageclass.yaml
Labels: component/deployment, ci/retry/e2e

#2878 rbd: log stderror when running modprobe
  internal/rbd/rbd_attach.go
  internal/rbd/rbd_util.go
Labels: component/rbd, logging, ci/retry/e2e

#2861 cephfs/rbd: add port sections to helm templates
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-psp.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-psp.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
Labels: component/rbd, component/deployment

#2883 helm-charts: Add selinuxMount flag to enable/disable /etc/selinux host mount
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-psp.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-psp.yaml
  charts/ceph-csi-rbd/values.yaml
Labels: component/deployment

#2877 helm: make ceph.conf ConfigMap name configurable
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/templates/ceph-conf.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/ceph-conf.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
Labels: component/deployment, ci/retry/e2e

#2886 e2e: consider not found error in deployment check
  e2e/deployment.go
Labels: component/testing, ci/retry/e2e

#2882 cephfs: refactor cephfs core functions
  internal/cephfs/controllerserver.go
  internal/cephfs/core/clone.go
  internal/cephfs/core/clone_test.go
  internal/cephfs/core/snapshot.go
  internal/cephfs/core/volume.go
  internal/cephfs/driver.go
  internal/cephfs/mounter/fuse.go
  internal/cephfs/mounter/kernel.go
  internal/cephfs/mounter/volumemounter.go
  internal/cephfs/nodeserver.go
  internal/cephfs/store/fsjournal.go
  internal/cephfs/store/volumeoptions.go
Labels: cleanup, component/cephfs, ci/retry/e2e

#2902 e2e: loadAppDeployment now sets ImagePullPolicy to PullIfNotPresent
  e2e/deployment.go
Labels: component/testing

#2854 doc: remove deprecated alpha1 reference of snapshot objects
  docs/snap-clone.md
Labels: component/docs, ci/skip/e2e

#2885 rbd: update image features
  charts/ceph-csi-rbd/values.yaml
  docs/deploy-rbd.md
  e2e/rbd.go
  e2e/rbd_helper.go
  examples/rbd/storageclass.yaml
  internal/rbd/controllerserver.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_util.go
  internal/rbd/rbd_util_test.go
Labels: component/rbd, ci/retry/e2e
