Repository ceph/ceph-csi, pull requests merged in 2022-12, with the labels that each got.

#3570 ci: use new `duffy` command for CentOS CI
  commitlint.groovy
  containerized-tests.groovy
  k8s-e2e-external-storage.groovy
  mini-e2e-helm.groovy
  mini-e2e.groovy
  upgrade-tests.groovy
Labels: component/testing

#3573 deploy: csidriver added to helper scripts
  examples/cephfs/plugin-deploy.sh
  examples/cephfs/plugin-teardown.sh
  examples/rbd/plugin-deploy.sh
  examples/rbd/plugin-teardown.sh
Labels: ci/skip/e2e, ci/skip/multi-arch-build, ok-to-test

#3586 cephfs: skip expand for BackingSnapshot volume
  internal/cephfs/controllerserver.go
Labels: component/cephfs, backport-to-release-v3.7, ok-to-test
