Repository ceph/ceph-csi, pull requests merged in 2022-11, with the labels that each got.

#3487 doc: add missing csidriver creation
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
Labels: bug, component/docs, ci/skip/e2e, ci/skip/multi-arch-build, backport-to-release-v3.7, ok-to-test

#3438 add commonLabels value
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/templates/ceph-conf.yaml
  charts/ceph-csi-cephfs/templates/csiplugin-configmap.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-http-service.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-serviceaccount.yaml
  charts/ceph-csi-cephfs/templates/provisioner-clusterrole.yaml
  charts/ceph-csi-cephfs/templates/provisioner-clusterrolebinding.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/templates/provisioner-http-service.yaml
  charts/ceph-csi-cephfs/templates/provisioner-role.yaml
  charts/ceph-csi-cephfs/templates/provisioner-rolebinding.yaml
  charts/ceph-csi-cephfs/templates/provisioner-serviceaccount.yaml
  charts/ceph-csi-cephfs/templates/secret.yaml
  charts/ceph-csi-cephfs/templates/storageclass.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/ceph-conf.yaml
  charts/ceph-csi-rbd/templates/csiplugin-configmap.yaml
  charts/ceph-csi-rbd/templates/encryptionkms-configmap.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-clusterrole.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-clusterrolebinding.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-http-service.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-serviceaccount.yaml
  charts/ceph-csi-rbd/templates/provisioner-clusterrole.yaml
  charts/ceph-csi-rbd/templates/provisioner-clusterrolebinding.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/templates/provisioner-http-service.yaml
  charts/ceph-csi-rbd/templates/provisioner-role.yaml
  charts/ceph-csi-rbd/templates/provisioner-rolebinding.yaml
  charts/ceph-csi-rbd/templates/provisioner-serviceaccount.yaml
  charts/ceph-csi-rbd/templates/secret.yaml
  charts/ceph-csi-rbd/templates/storageclass.yaml
  charts/ceph-csi-rbd/values.yaml
  scripts/install-helm.sh
Labels: component/deployment, ok-to-test

#3491 rebase: update node driver registar to latest version
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: rebase, ok-to-test

#2931 rbd: check volume details from original volumeID
  internal/rbd/nodeserver.go
Labels: component/rbd, dependency/ceph, keepalive, ok-to-test

#3422 rbd: setup encryption if rbdVol exits during CreateVol
  internal/rbd/controllerserver.go
Labels: component/rbd, ok-to-test

#3503 rebase: update csi to v1.7.0
  go.mod
  go.sum
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: rebase, ci/retry/e2e, ok-to-test

#3505 rbd: remove false error check in getDeviceSize
  internal/rbd/nodeserver.go
Labels: component/rbd, ok-to-test

#3497 ci: update minikube to v1.28.0
  build.env
Labels: component/testing, ci/retry/e2e, ci/skip/multi-arch-build, ok-to-test

#3506 e2e: use CurrentSpecReport for failed spec run
  e2e/cephfs.go
  e2e/nfs.go
  e2e/rbd.go
  e2e/upgrade-cephfs.go
  e2e/upgrade-rbd.go
Labels: component/testing, ok-to-test

#3509 ci: automatically remove `ok-to-test` and set it when queuing a PR
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3513 doc: lift the minimum supported version of ceph to v15.0.0
  README.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#3515 ci: do not immediately remove the `ok-to-test` label
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3521 ci: do not leave testing comments on merged PRs
  .github/workflows/pull-request-commentor.yaml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build, ok-to-test

#3524 rbd: ignore stdErr for ceph osd blocklist when there is no error
  internal/csi-addons/networkfence/fencing.go
Labels: component/rbd, ci/skip/e2e, backport-to-release-v3.7, ok-to-test

#3523 build: the go setup has been configured to 1.18 for retest build
  actions/retest/Dockerfile
Labels: component/build, ci/skip/e2e, ci/skip/multi-arch-build, ok-to-test

#3522 rbd: unset metadata if setmetadata is false
  e2e/rbd.go
  internal/rbd/rbd_util.go
Labels: component/rbd, ci/retry/e2e, backport-to-release-v3.7, ok-to-test

#3520 rebase: remove protobuf dependency locking
  go.mod
  go.sum
  internal/cephfs/controllerserver.go
  internal/cephfs/store/fsjournal.go
  internal/cephfs/util/util.go
  internal/rbd/rbd_util.go
  vendor/github.com/golang/protobuf/descriptor/descriptor.go
  vendor/github.com/golang/protobuf/jsonpb/decode.go
  vendor/github.com/golang/protobuf/proto/registry.go
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/github.com/golang/protobuf/ptypes/doc.go
  vendor/github.com/golang/protobuf/ptypes/duration.go
  vendor/github.com/golang/protobuf/ptypes/timestamp.go
  vendor/modules.txt
Labels: rebase, ci/retry/e2e, ok-to-test

#3529 build: update packages in api directory to the latest
  api/go.mod
  api/go.sum
Labels: component/build, ci/retry/e2e, ok-to-test

#3526 rebase: fix CVEs in the image
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/static_table.go
  vendor/golang.org/x/net/http2/hpack/tables.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/AUTHORS
  vendor/golang.org/x/oauth2/CONTRIBUTORS
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/time/AUTHORS
  vendor/golang.org/x/time/CONTRIBUTORS
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/sometimes.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/modules.txt
Labels: bug, rebase, security, component/build, ci/retry/e2e, ok-to-test

#3510 doc: fix mdl related failures
  README.md
  docs/ceph-csi-upgrade.md
  docs/ceph-mount-corruption.md
  docs/cephfs-snapshot-backed-volumes.md
  docs/deploy-rbd.md
  docs/design/proposals/cephfs-fscrypt.md
  docs/design/proposals/clusterid-mapping.md
  docs/design/proposals/encrypted-pvc.md
  docs/design/proposals/encryption-with-vault-tokens.md
  docs/design/proposals/intree-migrate.md
  docs/design/proposals/rbd-snap-clone.md
  docs/design/proposals/rbd-volume-healer.md
  docs/disaster-recovery.md
  docs/expand-pvc.md
  docs/intree-migrate.md
  docs/metrics.md
  docs/rbd-nbd.md
  docs/releases.md
  docs/snap-clone.md
  docs/static-pvc.md
  e2e/README.md
  examples/README.md
  scripts/mdl-style.rb
  tools/README.md
Labels: bug, component/docs, component/testing, ci/skip/e2e, ci/skip/multi-arch-build, ok-to-test

#3541 deploy: change the snapshot v1beta1 references from manifests
  examples/cephfs/snapshot.yaml
  examples/cephfs/snapshotclass.yaml
  examples/nfs/snapshotclass.yaml
  examples/rbd/snapshot.yaml
  examples/rbd/snapshotclass.yaml
Labels: cleanup, component/docs, ci/skip/e2e, ci/skip/multi-arch-build, ok-to-test

#3492 e2e: add snapshot count validation
  e2e/cephfs.go
  e2e/nfs.go
  e2e/upgrade-cephfs.go
Labels: component/testing, ok-to-test

#3551 rebase: update the kube dependencies to v1.25.4
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/nodes_util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: rebase
