Repository ceph/ceph-csi, pull requests merged in 2022-09, with the labels that each got.

#3361 rbd: change default FsGroupPolicy to "File" for RBD CSI driver
  charts/ceph-csi-rbd/templates/csidriver-crd.yaml
  deploy/rbd/kubernetes/csidriver.yaml
Labels: priority-1, component/rbd, backport-to-release-v3.7

#3372 ci: mirror Rook v1.10.0 image
  mirror/images.txt
Labels: component/testing

#3363 rbd: map only primary image
  internal/rbd/rbd_util.go
Labels: component/rbd, ci/retry/e2e, backport-to-release-v3.7

#3371 ci: use resync to sync helm charts
  deploy.sh
Labels: component/deployment, component/testing, component/build, ci/skip/e2e, ci/skip/multi-arch-build, backport-to-release-v3.7

#3377 rbd: create token and use it for vault SA everytime possible
  internal/kms/vault_sa.go
Labels: component/rbd, backport-to-release-v3.7

#3385 rbd: use blocklist range cmd, fallback if it fails
  internal/csi-addons/networkfence/fencing.go
Labels: component/rbd, ci/skip/e2e, backport-to-release-v3.7

#3391 deploy: update resizer to v1.6.0 version
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
Labels: component/deployment, ci/retry/e2e

#3398 use 4.0.0 version of attacher sidecar
  build.env
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
Labels: component/deployment, rebase, ci/retry/e2e

#3400 ci: run k8s v1.26 jobs on request
  jobs/k8s-e2e-external-storage.yaml
  jobs/mini-e2e.yaml
Labels: component/testing

#3401 rebase: update minikube to 1.27.0
  build.env
Labels: rebase, ci/retry/e2e

#3404 update sidecars to latest versions available
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
Labels: component/deployment, rebase, ci/retry/e2e

#3405 Revert changes done for v3.7.1 release
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: ci/retry/e2e
