Repository ceph/ceph-csi, pull requests merged in 2022-05, with the labels that each got.

#3074 doc: add Mergify badge to README
  README.md
Labels: Repo activity, component/docs, ci/skip/e2e

#3069 ci: prevent ERR trap inheritance for kubectl_retry
  scripts/utils.sh
Labels: component/testing, ci/skip/e2e, ci/retry/e2e

#3079 nfs: use latest liveness probe and node driver registrar
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
Labels: component/nfs

#3071 nfs: delete the CephFS volume when the export is already removed
  internal/nfs/controller/controllerserver.go
Labels: ci/retry/e2e, component/nfs, backport-to-release-v3.6

#3081 rbd: use `vaultAuthPath` variable name in error msg
  internal/kms/vault.go
Labels: component/rbd, logging, ci/skip/e2e, backport-to-release-v3.6

#3084 ci: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: component/testing, ci/skip/e2e

#3096 ci: Set permissions for GitHub actions
  .github/workflows/build-multi-stage.yaml
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/go-test.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/lint-extras.yaml
  .github/workflows/mod-check.yaml
  .github/workflows/publish-artifacts.yaml
  .github/workflows/retest.yaml
  .github/workflows/stale.yaml
  .github/workflows/test-retest-action.yaml
Labels: component/testing, ci/skip/e2e

#3097 ci: collect kubelet status
  system-status.sh
Labels: component/testing

#3091 util: support systems using the new cgroup v2 structure
  internal/util/pidlimit.go
Labels: component/util, ci/retry/e2e

#3100 ci: do not set `safe.directory` for commitlint checkout
  .github/workflows/commitlint.yaml
Labels: component/testing, ci/skip/e2e

#3101 rebase: bump nfsplugin to v4.0.0
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
Labels: rebase, ci/skip/e2e, component/nfs

#3080 rbd: consider rbd as default mounter if not set.
  internal/rbd/nodeserver.go
Labels: component/rbd, ci/retry/e2e, backport-to-release-v3.6

#3104 ci: add `ci/skip/multi-arch-build` label
  .github/workflows/build-multi-stage.yaml
  docs/development-guide.md
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3112 e2e: re-order deployment components
  e2e/cephfs.go
  e2e/nfs.go
  e2e/rbd.go
Labels: component/testing

#3070 e2e: retry getting Pods before executing commands
  e2e/pod.go
Labels: component/testing, ci/retry/e2e

#3122 e2e: remove TODO update nfs node-plugin with fix csi-driver-nfs#319
  e2e/nfs.go
Labels: bug, component/testing, ci/retry/e2e, component/nfs

#3044 cephfs: adjust RBAC for CephFS provisioner role
  deploy/cephfs/kubernetes/csi-provisioner-rbac.yaml
Labels: component/cephfs, component/deployment, ready-to-merge, ci/retry/e2e

#3127 chore(deps): Included dependency review
  .github/workflows/dependency-review.yaml
Labels: component/testing, ci/skip/e2e

#2912 doc: add proposal for CephFS fscrypt integration
  docs/design/proposals/cephfs-fscrypt.md
Labels: component/cephfs, component/docs, ci/skip/e2e

#3138 rbd: use vaultAuthPath variable name in error msg
  internal/kms/vault_sa.go
Labels: component/rbd, logging, ci/skip/e2e, backport-to-release-v3.6

#3141 ci: fix pylint error
  troubleshooting/tools/tracevol.py
Labels: bug, component/testing, ci/skip/e2e, backport-to-release-v3.6, ci/skip/multi-arch-build
