Repository ceph/ceph-csi, pull requests merged in 2022-06, with the labels that each got.

#3151 ci: add rook v1.9.4 image to mirror
  mirror/images.txt
Labels: component/testing

#3154 cephfs: skip NetNamespaceFilePath if the volume is pre-provisioned
  internal/cephfs/nodeserver.go
Labels: component/cephfs, backport-to-release-v3.6

#3160 ci: check more reviews in retest action
  actions/retest/main.go
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3172 build: release 3.6.2 template changes
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: component/build, ci/retry/e2e

#3132 rbd: add support for rbd striping
  docs/deploy-rbd.md
  e2e/rbd.go
  e2e/rbd_helper.go
  examples/rbd/storageclass.yaml
  internal/rbd/controllerserver.go
  internal/rbd/controllerserver_test.go
  internal/rbd/rbd_util.go
Labels: component/rbd, ci/retry/e2e

#3185 rebase: bump go-ceph version to v0.16.0
  Makefile
  go.mod
  go.sum
  vendor/github.com/ceph/go-ceph/cephfs/admin/clone.go
  vendor/github.com/ceph/go-ceph/cephfs/admin/clone_nautilus.go
  vendor/github.com/ceph/go-ceph/cephfs/admin/fsadmin.go
  vendor/github.com/ceph/go-ceph/cephfs/admin/metadata.go
  vendor/github.com/ceph/go-ceph/cephfs/admin/mgrmodule.go
  vendor/github.com/ceph/go-ceph/cephfs/admin/snapshot_metadata.go
  vendor/github.com/ceph/go-ceph/cephfs/admin/volume.go
  vendor/github.com/ceph/go-ceph/common/admin/nfs/admin.go
  vendor/github.com/ceph/go-ceph/common/admin/nfs/export.go
  vendor/github.com/ceph/go-ceph/internal/cutil/sync_buffer.go
  vendor/github.com/ceph/go-ceph/internal/cutil/sync_buffer_memcpy.go
  vendor/github.com/ceph/go-ceph/rados/ioctx.go
  vendor/github.com/ceph/go-ceph/rados/rados_read_op_assert_version.go
  vendor/github.com/ceph/go-ceph/rados/rados_set_locator.go
  vendor/github.com/ceph/go-ceph/rados/rados_write_op_assert_version.go
  vendor/github.com/ceph/go-ceph/rados/rados_write_op_remove.go
  vendor/github.com/ceph/go-ceph/rados/rados_write_op_setxattr.go
  vendor/github.com/ceph/go-ceph/rados/read_op_omap_get_vals_by_keys.go
  vendor/github.com/ceph/go-ceph/rados/read_op_read.go
  vendor/github.com/ceph/go-ceph/rados/watcher.go
  vendor/github.com/ceph/go-ceph/rbd/rbd_nautilus.go
  vendor/github.com/ceph/go-ceph/rbd/snapshot_rename.go
  vendor/modules.txt
Labels: rebase

#3170 deploy: make use of latest attacher release v3.5.0
  build.env
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/values.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
Labels: component/deployment, ci/retry/e2e

#3193 rebase: use v6.0.1 of snapshot client
  go.mod
  go.sum
  vendor/modules.txt
Labels: rebase, ci/retry/e2e

#3206 rbd: issue resync only if the force flag is set
  internal/rbd/replicationcontrollerserver.go
Labels: bug, component/rbd, ci/skip/e2e, backport-to-release-v3.6

#3211 ci: retest only one pr at a time & rebase if necessary
  actions/retest/main.go
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3214 ci: prevent panic in retest action on `nil` strings
  actions/retest/main.go
Labels: component/testing, ci/skip/e2e, ci/retry/e2e, ci/skip/multi-arch-build

#3216 revert: rbd: consider remote image health for primary
  internal/rbd/replicationcontrollerserver.go
  internal/rbd/replicationcontrollerserver_test.go
Labels: component/rbd, ci/skip/e2e, backport-to-release-v3.6, ci/skip/multi-arch-build

#3223 e2e: reduce defaultCloneCount to 3
  e2e/rbd.go
Labels: component/testing

#3213 e2e: pass non-empty Namespace/Name in deletePVCAndPV()
  e2e/pvc.go
Labels: component/testing, ci/retry/e2e

#3155 rbd: remove the clone in case of failure
  internal/rbd/clone.go
  internal/rbd/controllerserver.go
Labels: component/rbd, ci/retry/e2e
