Repository ceph/ceph-csi, pull requests merged in 2022-08, with the labels that each got.

#3274 Documentation cleanup
  README.md
  docs/capabilities.md
Labels: component/docs

#3275 ci: use latest :v17 Ceph contaimer-image again
  mirror/images.txt
Labels: component/testing

#3199 rbd: have dummy attacher implementation
  internal/rbd/controllerserver.go
Labels: component/rbd, ci/retry/e2e

#3273 Update relative path to ceph-config.yaml file
  docs/deploy-cephfs.md
Labels: component/deployment, component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#3283 ci: update minikube to v1.26.1
  build.env
Labels: rebase, component/testing, ci/retry/e2e

#3286 ci: update rook verion to v1.9.8
  mirror/images.txt
Labels: component/testing

#3288 ci: fix invalid mergifyio configuration
  .mergify.yml
Labels: ci/skip/e2e, ci/skip/multi-arch-build

#3290 rbd: consider mirror deamon state for ResyncVolume
  internal/rbd/replicationcontrollerserver.go
  internal/rbd/replicationcontrollerserver_test.go
Labels: component/rbd, ci/skip/e2e

#3291 rbd: Report remote peer readiness if Up and status.Unknown
  internal/rbd/replicationcontrollerserver.go
  internal/rbd/replicationcontrollerserver_test.go
Labels: component/rbd, ci/skip/e2e

#3304 ci: use ubuntu-latest for stale job
  .github/workflows/stale.yaml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3317 doc: correct e2e documentation formatting
  e2e/README.md
Labels: cleanup, component/docs, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3313 doc: update documentation for release 3.7.0
  README.md
  docs/ceph-csi-upgrade.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build, backport-to-release-v3.7

#3318 rebase: use latest kubernetes version
  go.mod
  go.sum
  vendor/k8s.io/client-go/tools/clientcmd/auth_loaders.go
  vendor/modules.txt
Labels: rebase, ci/retry/e2e

#3319 build: add mergify rule for backport PRs in release 3.7 branch
  .mergify.yml
Labels: Repo activity, component/build, ci/skip/e2e, ci/skip/multi-arch-build

#3323 doc: add nfs upgrade guide from 3.6 to 3.7
  docs/ceph-csi-upgrade.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build, backport-to-release-v3.7

#3326 ci: skip mutli-arch-build for doc and mergify prs
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3330 deploy: revert template changes of 3.7.0 to canary
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  scripts/minikube.sh
Labels: component/deployment, ci/retry/e2e

#3327 cleanup: replace github.com/pborman/uuid with github.com/google/uuid
  go.mod
  go.sum
  internal/journal/voljournal.go
  vendor/github.com/pborman/uuid/.travis.yml
  vendor/github.com/pborman/uuid/CONTRIBUTING.md
  vendor/github.com/pborman/uuid/CONTRIBUTORS
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/README.md
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/marshal.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/sql.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
  vendor/modules.txt
Labels: cleanup

#1996 Remove PSP related templates (once Kubernetes 1.25 is released)
  charts/ceph-csi-cephfs/templates/nodeplugin-psp.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-role.yaml
  charts/ceph-csi-cephfs/templates/nodeplugin-rolebinding.yaml
  charts/ceph-csi-cephfs/templates/provisioner-psp.yaml
  charts/ceph-csi-cephfs/templates/provisioner-role.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-psp.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-role.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-rolebinding.yaml
  charts/ceph-csi-rbd/templates/provisioner-psp.yaml
  charts/ceph-csi-rbd/templates/provisioner-role.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-nodeplugin-psp.yaml
  deploy/cephfs/kubernetes/csi-provisioner-psp.yaml
  deploy/nfs/kubernetes/csi-nodeplugin-psp.yaml
  deploy/nfs/kubernetes/csi-provisioner-psp.yaml
  deploy/rbd/kubernetes/csi-nodeplugin-psp.yaml
  deploy/rbd/kubernetes/csi-provisioner-psp.yaml
  docs/ceph-csi-upgrade.md
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  docs/rbd-nbd.md
  e2e/cephfs.go
  e2e/deploy-vault.go
  e2e/nfs.go
  e2e/rbd.go
  examples/kms/vault/vault-psp.yaml
  scripts/install-helm.sh
  scripts/install-snapshot.sh
  scripts/minikube.sh
  scripts/psp.yaml
  scripts/snapshot-controller-psp.yaml
Labels: component/deployment, dependency/k8s, keepalive

#3340 rbd: fix bug in kmip kms Decrypt function & improve error msg
  internal/kms/kmip.go
Labels: bug, component/rbd, ci/skip/e2e, backport-to-release-v3.7

#3349 rbd: modify stripSecret mechanism in logGRPC()
  go.mod
  go.sum
  internal/csi-common/utils.go
  vendor/github.com/csi-addons/spec/lib/go/replication/replication.pb.go
  vendor/modules.txt
Labels: component/rbd, logging, backport-to-release-v3.7

#3348 cephfs: return success if metadata operation not supported
  internal/cephfs/core/metadata.go
Labels: component/cephfs, ci/retry/e2e, backport-to-release-v3.7

#3351 ci: Set MINIKUBE_ISO_URL on minikube.sh up call
  single-node-k8s.sh
Labels: component/testing
