Repository ceph/ceph-csi, pull requests merged in 2023-05, with the labels that each got.

#3788 rbd: can exit early if image-meta.json does not exist
  internal/rbd/nodeserver.go
Labels: component/rbd

#3434 nfs: add support for `secTypes` parameter in StorageClass
  e2e/nfs.go
  examples/nfs/storageclass.yaml
  internal/nfs/controller/volume.go
Labels: dependency/ceph, component/nfs

#3797 ci: automatically add `ok-to-test` to PRs created by Mergify
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3809 ci: add GitHub Workflow to copy labels in Mergify created PRs
  .github/workflows/mergify-copy-labels.yaml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3810 ci: add `ok-to-test` label to all PRs in the merge queue
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3816 ci: Mergify copy-labels requires empty `labels:` value
  .github/workflows/mergify-copy-labels.yaml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3815 ci: fix author=mergify[bot]
  .mergify.yml
Labels: bug, Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3818 ci: Mergify copy-labels requires empty string for `labels:`
  .github/workflows/mergify-copy-labels.yaml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3821 ci: include ci/skip/.. labels for copying into merge queue PRs
  .github/workflows/mergify-copy-labels.yaml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3823 ci: use modified gha-mergify-merge-queue-labels-copier Action
  .github/workflows/mergify-copy-labels.yaml
  actions/gha-mergify-merge-queue-labels-copier.yaml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3829 ci: check for `mergify/merge-queue/` string, with `-`
  actions/gha-mergify-merge-queue-labels-copier/action.yaml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3836 ci: fix modified gha-mergify-merge-queue-labels-copier Action
  .github/workflows/mergify-copy-labels.yaml
  actions/gha-mergify-merge-queue-labels-copier/action.yaml
Labels: bug, Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3751 deploy: fix a bug of ceph-csi helm chart rendered duplicate affinities in rbd and cephfs
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
Labels: bug, component/deployment, ci/retry/e2e, ci/skip/multi-arch-build

#3843 ci: install Helm with script located on GitHub
  build.env
  deploy.sh
  scripts/Dockerfile.test
Labels: component/testing, ci/skip/multi-arch-build, backport-to-release-v3.8

#3858 ci: trigger `Add comment` workflow for "opened" prs
  .github/workflows/pull-request-commentor.yaml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3862 ci: fix pull-request-commentor workflow
  .github/workflows/pull-request-commentor.yaml
Labels: bug, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3866 ci: fix syntax error in `pull-request-commenter` GitHub Workflow
  .github/workflows/pull-request-commentor.yaml
Labels: bug, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3869 ci: remove `\` from GitHub Workflow if condition
  .github/workflows/pull-request-commentor.yaml
Labels: bug, Priority-0, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3870 ci: `github.event.pull_request.merged` is a boolean, not a string
  .github/workflows/pull-request-commentor.yaml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build
