Repository ceph/ceph-csi, pull requests merged in 2023-03, with the labels that each got.

#3695 doc: update the meeting schedule in readme
  README.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#3724 ci: update mirroring container-images job for new OCP
  mirror/mirror-buildconfig.yaml
  mirror/mirror-cronjob.yaml
Labels: cleanup, component/testing

#3725 ci: run registry garbage collection every week
  deploy/docker-gc.yaml
Labels: component/testing
