Repository ceph/ceph-csi, pull requests merged in 2023-02, with the labels that each got.

#3634 ci: drop `ok-to-test` label when a PR is rebased
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3637 ci: `bot_account` is not available for our Mergify usage
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3655 doc: Add basic upgrade documentation for Helm Charts
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-rbd/README.md
Labels: DNM, component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#3656 ci: prevent always removing `ok-to-test` label
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3665 ci: remove deprecated `rebase_fallback` from .mergify.yml
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3666 e2e: fix typo
  e2e/cephfs.go
Labels: bug, component/testing, logging, ci/skip/e2e, ci/skip/multi-arch-build, ok-to-test

#3672 ci: use `context.issue.number` for removing `ok-to-test`
  .github/workflows/pull-request-commentor.yaml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build, ok-to-test

#3673 ci: add `/api` to dependabot configuration
  .github/dependabot.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build, ok-to-test

#3681 ci: only add `ok-to-test` if there are no pending CentOS jobs
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3651 cephfs: use shallow volumes for the ROX accessMode
  docs/deploy-cephfs.md
  e2e/cephfs.go
  examples/cephfs/storageclass.yaml
  internal/cephfs/controllerserver.go
  internal/cephfs/store/volumeoptions.go
  internal/cephfs/store/volumeoptions_test.go
  internal/nfs/controller/controllerserver.go
Labels: component/cephfs, ci/retry/e2e, ok-to-test

#3686 deploy: update templates to 3.8.0
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/deployment, ok-to-test

#3688 ci: do not add `ok-to-test` if CentOS jobs were successful
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3689 revert: revert back 3.8.0 template changes
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/deployment

#3690 CI: Update mergify rules
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, ci/skip/multi-arch-build
