Repository ceph/ceph-csi, pull requests merged in 2023-04, with the labels that each got.

#3738 fix: ceph name and version not matching in readme support matrix
  README.md
Labels: bug, component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#3735 e2e: remove extra check for snapshot count
  e2e/cephfs.go
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3742 fix: configuring cephfs snapshots and clones
  examples/README.md
Labels: bug, component/docs, ready-to-merge, ci/skip/e2e, ci/skip/multi-arch-build

#3734 ci: update minikube to 1.30
  build.env
Labels: Repo activity, component/testing, ci/skip/multi-arch-build

#3732 ci: remove kubernetes 1.23 support
  jobs/k8s-e2e-external-storage.yaml
  jobs/mini-e2e.yaml
Labels: component/testing, ready-to-merge

#3731 ci: remove Kubernetes 1.23 from github action
  .github/workflows/pull-request-commentor.yaml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3745 ci: update github actions for k8s 1.27
  .github/workflows/pull-request-commentor.yaml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3764 doc: Correct few doc errors
  docs/deploy-cephfs.md
  docs/development-guide.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#3768 build: update golang to 1.19.8
  build.env
Labels: component/build, backport-to-release-v3.8

#3744 ci: update mergify rules for kubernetes 1.27
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3781 util: Limit cryptsetup PBKDF memory usage
  internal/util/cryptsetup.go
Labels: component/rbd, component/util, backport-to-release-v3.8
