Repository ceph/ceph-csi, pull requests merged in 2023-06, with the labels that each got.

#3868 rebase: update k8s external-snapshotter to v6.2.2
  build.env
Labels: rebase, ci/skip/multi-arch-build, ok-to-test

#3874 ci: use `github.event.label.name` for check in pull-request-commenter
  .github/workflows/pull-request-commentor.yaml
Labels: bug, component/testing, ci/skip/e2e, ci/skip/multi-arch-build, ok-to-test

#3871 deploy: update CSI sidecars to latest versions available
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/deployment, ci/skip/multi-arch-build

#3876 cleanup: no need for disabling the apache-arrow-centor repository anymore
  scripts/Dockerfile.devel
Labels: cleanup, ci/skip/multi-arch-build

#3878 doc: Corrections to retest-action doc
  actions/retest/README.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#3877 ci: use the "ceph-csi-bot" account for commenting on PRs
  .github/workflows/pull-request-commentor.yaml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3883 ci: prevent Retest Workflow from running on forked repos
  .github/workflows/retest.yaml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3905 ci: fix pr-commentor for merge queue draft pr
  .github/workflows/mergify-copy-labels.yaml
  .github/workflows/pull-request-commentor.yaml
Labels: bug, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3906 helm: add imagePullSecrets for helm charts
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
Labels: component/deployment, ci/retry/e2e, ci/skip/multi-arch-build

#3908 ci: remove checks for k8s 1.24 ci tests
  .github/workflows/pull-request-commentor.yaml
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#3926 ci: use CentOS Stream 9 for Jenkins Jobs Builder image
  deploy/Dockerfile
Labels: component/testing

#3909 ci: remove k8s 1.24 support
  jobs/k8s-e2e-external-storage.yaml
  jobs/mini-e2e.yaml
Labels: component/testing

#3884 rbd: remove grpc and csi-addons import from rbd/replication.go
  internal/csi-addons/rbd/replication.go
  internal/csi-addons/rbd/replication_test.go
  internal/rbd/errors.go
  internal/rbd/replication.go
Labels: component/rbd

#3924 rbd: migration of replication service from controller server
  internal/csi-addons/rbd/replication.go
  internal/rbd/driver/driver.go
Labels: component/rbd, ci/skip/e2e, ci/skip/multi-arch-build

#3894 rbd: get lastsyncbytes and lastsycduration for volrep
  go.mod
  go.sum
  internal/csi-addons/rbd/replication.go
  internal/csi-addons/rbd/replication_test.go
  vendor/github.com/csi-addons/spec/lib/go/replication/replication.pb.go
  vendor/modules.txt
Labels: component/rbd, ci/skip/e2e, ci/skip/multi-arch-build

#3930 rbd: (lastSyncInfo)handle last sync duration being empty case
  internal/csi-addons/rbd/replication.go
  internal/csi-addons/rbd/replication_test.go
Labels: component/rbd, ci/skip/e2e, ci/skip/multi-arch-build

#3936 mergify: add support for 3.9 backports
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, ci/skip/multi-arch-build

#3947 build: use urllib3 < 2 with Jenkins jobs Builder
  deploy/Dockerfile
Labels: ready-to-merge, component/build

#3948 cleanup: correct the comment in csi-addons/rbd
  internal/csi-addons/rbd/network_fence.go
  internal/csi-addons/rbd/reclaimspace.go
Labels: cleanup, ci/skip/e2e, ci/skip/multi-arch-build

#3956 ci: remove `/retest all` command for Jenkins jobs
  jobs/k8s-e2e-external-storage.yaml
  jobs/mini-e2e.yaml
  jobs/upgrade-tests.yaml
Labels: component/testing, ready-to-merge
