Repository ceph/ceph-csi, pull requests merged in 2023-12, with the labels that each got.

#4295 ci: the release-v3.10 branch needs Kubernetes 1.28 jobs
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#4296 revert: revert to 3.10-canary
  build.env
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: ci/retry/e2e

#4301 ci: Change upgrade version
  build.env
Labels: component/testing

#4298 helm: add default false value for --enable-read-affinity
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  scripts/install-helm.sh
Labels: component/deployment, ci/retry/e2e, backport-to-release-v3.10

#4316 cephfs: fix network fencing admin id
  internal/csi-addons/cephfs/network_fence.go
Labels: bug, component/cephfs

#4319 deploy: use release repository for csi-resizer
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
Labels: component/deployment, ci/skip/multi-arch-build

#4321 cephFS: fix fetchIP to support more formats
  internal/csi-addons/networkfence/fencing.go
  internal/csi-addons/networkfence/fencing_test.go
Labels: bug

#4335 build: create /etc/selinux/config in case it is missing
  deploy/cephcsi/image/Dockerfile
  scripts/Dockerfile.devel
  scripts/Dockerfile.test
Labels: Backport, component/build

#4336 deploy: update templates to v3.10.1
  README.md
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: ci/skip/multi-arch-build
