Repository ceph/ceph-csi, pull requests merged in 2024-08, with the labels that each got.

#4746 doc: Remove podSecurityPolicy from helm docs
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-rbd/README.md
Labels: component/deployment, component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#4752 ci: only update jobs, do not check views
  deploy/Makefile
Labels: component/testing

#4754 ci: prevent incorrect pattern matching for `skipping ci` command
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#4759 ci: add test for uncommitted changes in deploy directory
  .github/workflows/go-test.yaml
  .mergify.yml
  Makefile
Labels: component/testing, ci/skip/e2e, backport-to-release-v3.11

#4764 ci: update yaml to deploy kube 1.31
  jobs/k8s-e2e-external-storage.yaml
  jobs/mini-e2e.yaml
Labels: component/testing

#4766 ci: remove feature gates
  scripts/minikube.sh
Labels: component/testing

#4770 build: prepare of 3.12.0
  PendingReleaseNotes.md
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/build

#4776 helm: don't specify default topology domainlabels in rbd chart
  charts/ceph-csi-rbd/values.yaml
Labels: component/deployment, backport-to-release-v3.12

#4785 ci: update CSI_UPGRADE_VERSION to v3.12.1
  build.env
Labels: component/testing, ci/skip/e2e

#4786 build: Use Go v1.22.5
  build.env
  go.mod
Labels: component/build, ci/skip/e2e

#4791 rbd: add image size in toSnapshot
  internal/rbd/snapshot.go
Labels: component/rbd, ci/retry/e2e, backport-to-release-v3.12

#4789 ci: update mergify config to replace,remove deprecated attributes
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#4803 doc: Remove the 400 snapshot limitation
  docs/snap-clone.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#4797 ci: pass the correct account token for Snyk jobs
  .github/workflows/snyk-container-image.yaml
  .github/workflows/snyk.yaml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#4808 rbd: add a check for CSI pv
  internal/rbd/rbd_healer.go
Labels: bug, component/rbd, backport-to-release-v3.12

#4794 rbd: move common functions for VolumeGroup structs into own type
  internal/rbd/group/util.go
  internal/rbd/group/volume_group.go
Labels: component/rbd

#4801 helm: Optionally set userID and userKey in cephfs chart.
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/templates/secret.yaml
  charts/ceph-csi-cephfs/values.yaml
Labels: component/deployment, ci/skip/multi-arch-build
