Repository ceph/ceph-csi, pull requests merged in 2024-04, with the labels that each got.

#4527 doc: csi driver object options
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-rbd/README.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#4525 cleanup: rename EncryptionTypeString() to EncryptionType.String()
  e2e/rbd.go
  internal/journal/voljournal.go
  internal/util/crypto.go
  internal/util/crypto_test.go
Labels: cleanup

#4537 ci: upgrade_version update
  build.env
Labels: component/testing

#4533 CI: remove used rules from mergify config file
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, ci/skip/multi-arch-build

#4542 ci: add volumesnapshotclass creation
  k8s-e2e-external-storage.groovy
Labels: component/testing

#4546 ci: run tests with more logs
  run-k8s-external-storage-e2e.sh
Labels: component/testing

#4545 ci: run snapshot tests and expand tests
  scripts/k8s-storage/driver-cephfs.yaml
Labels: component/testing, ci/skip/multi-arch-build

#4554 build: use Go 1.21.9 to include latest security fixes
  build.env
  go.mod
Labels: bug, component/build, backport-to-release-v3.10, backport-to-release-v3.11

#4557 ci: do not add the `ok-to-test` label if there is a conflict
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#4558 cleanup: client cert decoding is not required
  internal/kms/azure_vault.go
Labels: bug, cleanup, backport-to-release-v3.11

#4566 util: add support to configure mirror daemon count
  charts/ceph-csi-rbd/values.yaml
  deploy/csi-config-map-sample.yaml
  internal/rbd/rbd_util.go
  internal/util/csiconfig.go
  internal/util/csiconfig_test.go
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/csi-config-map.go
Labels: component/rbd, component/util

#4522 rbd: add ParentInTrash parameter in rbdImage struct
  e2e/rbd.go
  internal/rbd/rbd_util.go
Labels: component/rbd, component/testing, backport-to-release-v3.11

#4573 deploy: update CSI sidecars to latest versions available
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/build, backport-to-release-v3.11

#4568 ci: add more tests for cephfs external test
  scripts/k8s-storage/driver-cephfs.yaml
Labels: component/testing, ci/skip/multi-arch-build

#4577 build: include MirrorDaemonCount in the ConfigMap API
  api/deploy/kubernetes/csi-config-map.go
Labels: bug, component/build, ci/skip/e2e

#4578 ci: do not require Kubernetes 1.26 tests for the devel branch
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#4584 build: prevent "Operation not supported" failures while extracting Golang in CI jobs
  scripts/Dockerfile.test
Labels: component/build, ci/skip/e2e, ci/skip/multi-arch-build, backport-to-release-v3.10, backport-to-release-v3.11
