Repository ceph/ceph-csi, pull requests merged in 2024-01, with the labels that each got.

#4359 rebase: update jobs for kubernetes 1.29
  jobs/k8s-e2e-external-storage.yaml
  jobs/mini-e2e.yaml
Labels: rebase

#4352 deploy: update csi sidecars to latest versions
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/deployment, rebase

#4354 ci: update github actions for k8s-1.29
  .github/workflows/pull-request-commentor.yaml
Labels: component/testing

#4363 allow modify fsGroupPolicy for csidriver
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  charts/ceph-csi-cephfs/values.yaml
Labels: component/cephfs, component/deployment, ci/retry/e2e

#4364 cleanup: simplify `rbdGetDeviceList()`
  internal/rbd/rbd_attach.go
Labels: cleanup, component/rbd

#4378 cephfs: do not run `modprobe` if support is compiled into the kernel
  internal/cephfs/mounter/kernel.go
  internal/cephfs/mounter/kernel_test.go
  internal/cephfs/mounter/volumemounter.go
  internal/cephfs/nodeserver.go
  internal/cephfs/nodeserver_test.go
Labels: bug, component/cephfs, backport-to-release-v3.10

#4401 ci: retry pulling container images up to 10x
  k8s-e2e-external-storage.groovy
Labels: component/testing, ready-to-merge

#4403 ci: allow missing `RUN_DISPLAY_URL` variable in Jenkins Jobs
  deploy/Makefile
Labels: component/testing

#4406 ci: replace inline `dsl:` script by Groovy files
  jjb-deploy.groovy
  jjb-validate.groovy
  jobs/build-images.yaml
  jobs/jjb-deploy.yaml
  jobs/jjb-validate.yaml
Labels: component/testing

#4407 ci: correct the format of `pipeline-scm.scm`
  jobs/build-images.yaml
  jobs/jjb-deploy.yaml
  jobs/jjb-validate.yaml
Labels: component/testing

#4408 ci: CentOS CI networking is stable again, remove pull-loop
  k8s-e2e-external-storage.groovy
Labels: component/testing
