Repository ceph/ceph-csi, pull requests merged in 2024-02, with the labels that each got.

#4405 doc: Update README.md with slack invite and channel links
  README.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#4416 build: update for 3.10.2 release
  README.md
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  docs/ceph-csi-upgrade.md
Labels: component/build

#4429 util: log repication RequestID
  internal/csi-common/utils.go
  internal/csi-common/utils_test.go
Labels: bug, ci/skip/e2e, backport-to-release-v3.10

#4424 ci: update the upgrade_version
  build.env
Labels: component/testing

#4434 deploy: make the csi-*plugin containers the default for kubectl commands
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/deployment, ci/skip/multi-arch-build

#4355 ci: update mergify rules for kubernetes 1.29
  .github/workflows/pull-request-commentor.yaml
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#4439 rebase: update external-snapshotter client to v7
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/nfs.go
  e2e/rbd_helper.go
  e2e/snapshot.go
  e2e/utils.go
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumegroupsnapshot/v1alpha1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumegroupsnapshot/v1alpha1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumegroupsnapshot/v1alpha1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/clientset/versioned/typed/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/clientset/versioned/typed/volumesnapshot/v1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotcontent.go
  vendor/modules.txt
Labels: rebase, ci/retry/e2e, ci/skip/multi-arch-build

#4452 ci: update the mergify rule to exclude k8s 1.25
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#4450 rebase: use Helm client 3.14.1 for generating charts
  build.env
Labels: component/deployment, rebase

#4457 ci: prepare Jenkins jobs for Kubernetes 1.30
  jobs/k8s-e2e-external-storage.yaml
  jobs/mini-e2e.yaml
Labels: component/testing
