Repository ceph/ceph-csi, pull requests merged in 2024-05, with the labels that each got.

#4598 cleanup: incorrect fuserecovery logging
  internal/cephfs/fuserecovery.go
  internal/cephfs/nodeserver.go
  internal/cephfs/store/volumeoptions.go
  internal/util/util.go
Labels: cleanup

#4606 rebase: update minikube to 1.33
  build.env
Labels: rebase, ci/skip/multi-arch-build

#4609 cephfs: upgrade fscrypt version to fix concurrency issue
  go.mod
  go.sum
  vendor/github.com/google/fscrypt/actions/context.go
  vendor/github.com/google/fscrypt/actions/policy.go
  vendor/github.com/google/fscrypt/crypto/crypto.go
  vendor/github.com/google/fscrypt/crypto/rand.go
  vendor/github.com/google/fscrypt/filesystem/filesystem.go
  vendor/github.com/google/fscrypt/filesystem/mountpoint.go
  vendor/github.com/google/fscrypt/metadata/config.go
  vendor/github.com/google/fscrypt/metadata/metadata.pb.go
  vendor/github.com/google/fscrypt/metadata/policy.go
  vendor/github.com/google/fscrypt/security/privileges.go
  vendor/modules.txt
Labels: bug, component/cephfs, backport-to-release-v3.11

#4613 cephfs: upgrade fscrypt version to fix concurrency issue (backport #4609)
  go.mod
  go.sum
  vendor/github.com/google/fscrypt/actions/context.go
  vendor/github.com/google/fscrypt/actions/policy.go
  vendor/github.com/google/fscrypt/crypto/crypto.go
  vendor/github.com/google/fscrypt/crypto/rand.go
  vendor/github.com/google/fscrypt/filesystem/filesystem.go
  vendor/github.com/google/fscrypt/filesystem/mountpoint.go
  vendor/github.com/google/fscrypt/metadata/config.go
  vendor/github.com/google/fscrypt/metadata/metadata.pb.go
  vendor/github.com/google/fscrypt/metadata/policy.go
  vendor/github.com/google/fscrypt/security/privileges.go
  vendor/modules.txt
Labels: bug, component/cephfs, ready-to-merge

#4622 ci: install ruby-devel in test container
  scripts/Dockerfile.test
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build, backport-to-release-v3.10, backport-to-release-v3.11

#4621 Fix the Slack invite link on the README
  README.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#4608 util: Removing JoinError in favor of fmt.Errorf
  internal/cephfs/core/volume.go
  internal/cephfs/store/volumeoptions.go
  internal/journal/omap.go
  internal/rbd/rbd_util.go
  internal/util/cephcmds.go
  internal/util/connection.go
  internal/util/errors.go
  internal/util/errors_test.go
Labels: cleanup

#4626 ci: Use temporary directory for unit tests
  internal/rbd/nodeserver_test.go
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#4631 cephfs: close dir
  internal/cephfs/nodeserver.go
Labels: bug, component/cephfs, backport-to-release-v3.11

#4647 ci: remove k8s 1.30 tests check
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#4650 ci: update centos to 9 stream
  k8s-e2e-external-storage.groovy
Labels: component/testing, ready-to-merge
