Repository ceph/ceph-csi, pull requests merged in 2024-03, with the labels that each got.

#4464 fscrypt: create a new blank key sized according to the passphrase
  internal/util/fscrypt/fscrypt.go
Labels: component/cephfs, component/rbd, component/util

#4483 cleanup: use real version for k8s.io/pod-security-admission instead of v0.0.0
  go.mod
  vendor/modules.txt
Labels: cleanup, ci/skip/e2e, ci/skip/multi-arch-build

#4475 helm: Include seLinuxMount only if KubeVersion greater or equal of 1.25
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  charts/ceph-csi-rbd/templates/csidriver-crd.yaml
Labels: component/deployment, ci/skip/e2e, ci/skip/multi-arch-build

#4469 doc: Update capabilities readme to solve to open permissions in it
  docs/capabilities.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#4291 support nbd on euler or arm
  internal/rbd/rbd_attach.go
Labels: component/rbd

#4495 cleanup: correct typo in `NewCSIVolumeroupJournal()` function
  internal/journal/volumegroupjournal.go
Labels: cleanup, ci/skip/e2e

#4498 cleanup: do not pass EncodingVersion to `GenerateVolID()`
  internal/cephfs/store/fsjournal.go
  internal/cephfs/util/util.go
  internal/rbd/globals.go
  internal/rbd/rbd_journal.go
  internal/util/util.go
  internal/util/volid.go
  internal/util/volid_test.go
Labels: cleanup

#4512 helm: CSIDriver add labels and seLinuxMount disabling method
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/csidriver-crd.yaml
  charts/ceph-csi-rbd/values.yaml
Labels: component/deployment

#4504 cephfs: add support for encryption in ceph-csi-cephfs chart
  charts/ceph-csi-cephfs/templates/nodeplugin-clusterrole.yaml
  charts/ceph-csi-cephfs/templates/provisioner-clusterrole.yaml
Labels: bug, component/cephfs, component/deployment, backport-to-release-v3.10

#4459 rbd: make pool optional in rbd sc if topologyconstraints are present
  charts/ceph-csi-rbd/templates/storageclass.yaml
  charts/ceph-csi-rbd/values.yaml
  e2e/rbd.go
  e2e/rbd_helper.go
  examples/rbd/storageclass.yaml
  internal/rbd/controllerserver.go
  internal/rbd/rbd_journal.go
  internal/rbd/rbd_util.go
Labels: component/rbd, component/deployment

#4519 helm: fix seLinuxMount option for csi driver object
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  charts/ceph-csi-rbd/templates/csidriver-crd.yaml
Labels: bug, component/deployment
