Repository ceph/ceph-csi, pull requests merged in 2025-06, with the labels that each got.

#5360 doc: fix format in helm chart
  charts/ceph-csi-rbd/README.md
Labels: bug, component/deployment, component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#5364 doc: add `v3` symlink to get current versions in pkg.go.dev
  v3
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build

#5372 nfs: return success if export already exists
  internal/nfs/controller/volume.go
Labels: component/nfs, backport-to-release-v3.14

#5382 build: prepare for v3.14.1
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/build

#5384 revert: prepare for v3.14.1
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: ready-to-merge

#5392 flattenClonedRbdImages may require namespace
  internal/rbd/controllerserver.go
  internal/rbd/rbd_util.go
Labels: backport-to-release-v3.14
