Repository ceph/ceph-csi, pull requests merged in 2025-09, with the labels that each got.

#5535 build: remove `ceph_preview` build-tag
  Makefile
Labels: cleanup, component/build, ci/skip/e2e

#5538 nvmeof: cleanup resources when CreateVolume fails
  internal/nvmeof/controller/controllerserver.go
Labels: component/nvme-of

#5561 nvmeof: combine create\delete subsystem and listener
  internal/nvmeof/controller/controllerserver.go
Labels: ci/skip/e2e, component/nvme-of

#5586 ci(mergify): set update_bot_account
  .mergify.yml
Labels: Repo activity, ci/skip/e2e, ci/skip/multi-arch-build

#5603 cleanup: remove duplication code of k8s GetSecret
  internal/kms/aws_metadata.go
  internal/kms/aws_sts_metadata.go
  internal/kms/azure_vault.go
  internal/kms/keyprotect.go
  internal/kms/kmip.go
  internal/kms/secretskms.go
  internal/kms/vault_sa.go
  internal/kms/vault_tokens.go
  internal/rbd/rbd_healer.go
Labels: cleanup
