Repository ceph/ceph-csi, pull requests merged in 2025-03, with the labels that each got.

#5181 build: update rook version to v1.16.4
  build.env
Labels: component/build

#5190 build: the Fedora container image is now maintained at quay.io
  scripts/Dockerfile.test
Labels: component/build, ci/skip/e2e, backport-to-release-v3.13

#5189 build: prepare of 3.13.1
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/build

#5206 rbd: use ListChildrenAttributes() instead of ListChildren()
  go.mod
  go.sum
  internal/rbd/clone.go
  internal/rbd/controllerserver.go
  internal/rbd/rbd_util.go
  vendor/github.com/aws/smithy-go/CHANGELOG.md
  vendor/github.com/aws/smithy-go/go_module_metadata.go
  vendor/github.com/ceph/go-ceph/rbd/encryption.go
  vendor/github.com/ceph/go-ceph/rbd/encryption_load2.go
  vendor/github.com/ceph/go-ceph/rbd/encryption_opt_luks.go
  vendor/github.com/ceph/go-ceph/rbd/snapshot_nautilus.go
  vendor/modules.txt
Labels: component/rbd

#5208 ci: update rule for ci/skip/e2e
  .mergify.yml
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#5213 ci: update CSI_UPGRADE_VERSION to v3.13.1
  build.env
Labels: component/testing

#5217 rbd: add one depth for softlimit of snapshot for restore PVC
  internal/rbd/rbd_util.go
Labels: component/rbd

#5231 ci: cleanup golangci configuration
  scripts/golangci.yml.in
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#5235 ci: run upgrade tests with Kubernetes 1.32
  jobs/upgrade-tests.yaml
Labels: component/testing, ready-to-merge

#5090 cephfs: upgrading mount syntax
  e2e/cephfs.go
  internal/cephfs/mounter/kernel.go
  internal/cephfs/store/volumeoptions.go
Labels: component/cephfs

#5242 ci: fix codespell and lint issues
  .github/workflows/retest.yaml
  scripts/codespell.conf
  troubleshooting/tools/tracevol.py
Labels: bug, component/testing, ci/skip/e2e, ci/skip/multi-arch-build
