Repository ceph/ceph-csi, pull requests merged in 2025-04, with the labels that each got.

#5248 rbd: Register FenceController only once
  internal/rbd/driver/driver.go
Labels: component/rbd

#5264 rebase: update golang.org/x/oauth2 to v0.27.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: rebase

#5268 build: prepare for v3.14.0
  build.env
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: component/build

#5272 util: fix bug in health checker
  internal/health-checker/manager.go
  internal/health-checker/manager_test.go
Labels: bug, component/util, backport-to-release-v3.14

#5281 ci: install awk in Fedora test container-image
  scripts/Dockerfile.test
Labels: component/testing, ci/skip/e2e, ci/skip/multi-arch-build, backport-to-release-v3.13, backport-to-release-v3.14

#5288 helm: mark userID and userKey required in secret
  PendingReleaseNotes.md
  charts/ceph-csi-cephfs/templates/secret.yaml
Labels: component/deployment

#5289 ci: add `ok-to-test` label after Mergify rephrase
  .mergify.yml
Labels: Repo activity, component/testing, ci/skip/e2e, ci/skip/multi-arch-build

#5243 e2e: test for PVC with volumeBindingMode on helm installation
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/pvc.go
  e2e/utils.go
Labels: component/deployment, component/testing

#5294 doc: Update cephfs caps
  docs/capabilities.md
Labels: component/docs, ci/skip/e2e, ci/skip/multi-arch-build
